### ISSUE TITLE
Editing The Acceptance Criteria Of Scenarios

### ISSUE THREAD

**Issue by mertcan-ozkan** [bounswe/bounswe2022group3#103]
The [requirements page](https://github.com/bounswe/bounswe2022group3/wiki/Requirements) has been modified after the scenarios were created. Therefore, the acceptance criteria sections of these scenarios should be modified to match the new version of requirements. You can reach the corresponding pages here:
-[Scenario one]( https://github.com/bounswe/bounswe2022group3/wiki/Scenario-1)
-[Scenario two]( https://github.com/bounswe/bounswe2022group3/wiki/Scenario-2)
-[Scenario three]( https://github.com/bounswe/bounswe2022group3/wiki/Scenario-3)
Deadline: 15.04.2022, before first milestone submission
Reviewer: @muhammetssen

**Comment by ersoykadir** [comment]
# Scenario 1
## Old Acceptance criteria with old requirements
> - 1.2.8 Learners shall be able to join the attendance list of the event that they would like to participate, for their enrolled classes.
>  - 1.3.3 Lecturers shall be able to organize and schedule meetings.
>  - 1.3.3.1 If there are not enough participation event should be cancelled.
>  - 1.3.4 Lecturers shall be able to create a poll, allowed to be filled by the students enrolled in their course.
## New one
> - 1.3.8.1. Lecturers shall be able to create polls, allowed to be filled by the students enrolled in their course. The anonimity and/or the obligation of the poll shall be decided by the lecturer and declared to the students.
> - 1.3.8.2. Lecturers shall be able to organize and schedule events. The scope of the event depends on the lecturer's initiative. It can be public or private, face to face or online, free or needs a fee to enter.
>   - 1.3.8.2.1. If the event is private, lecturer has to provide list of learners who can attend the event. These users shall be notified.
> - 1.3.8.3. The lecturer has the right to edit details (date/time, title, description, location, quota, list of attendees, fee) of the event.
> - 1.3.8.4. The lecturer has the right to cancel the event.
> - 1.3.11 Users shall be able to join the attendance list of the event that they would like to participate, for their enrolled classes.

Requirement related to joining events(1.3.11) was missing after requirements were updated, so added it back.

**Comment by yilmaz-burak** [comment]
Scenario #3 -> @yilmaz-burak responsible for new requirement replacement

**Comment by yilmaz-burak** [comment]
# Scenario 3

## Old Acceptance Criteria
* 1.2.4. Learners shall be able to use note taking feature.
* 2.3.1. The system shall provide learners the ability to create a note taking page.
* 2.3.2. The system shall provide learners the ability to save notes in their profile page.
* 2.3.3. The system shall show the saved notes of the learner in their profile page.
* 2.3.3.1. The system should provide learners the option to sort notes according to date or popularity.
* 2.3.3.2. The system should provide learners the option to show previous notes according to filtered systems.
* 2.3.3.2.1. The note filtered system should enable learners to filter course name or lecturer.
* 2.3.4. The system shall provide learners the ability delete or rearrange note taking page.
* 2.3.5. The system shall provide registered learners the ability to connect notes, annotate and tag them.
* 2.3.6. The system shall provide learners the ability to share their notes with others.


## New Acceptance Criteria
* 1.3.4. Users shall be able to use the note taking features (described in 2.3.)
* 2.3.1. The system shall provide learners the ability to create a note taking page.
* 2.3.2. The system shall provide learners the ability to save notes in their profile page.
* 2.3.3. The system shall show the saved notes of the learner in their profile page.
* 2.3.3.1. The system should provide learners the option to sort notes according to date or popularity.
* 2.3.3.2. The system should provide learners the option to show previous notes according to filtered systems.
* 2.3.3.2.1. The note filtered system should enable learners to filter course name or lecturer.
* 2.3.4. The system shall provide learners the ability delete or rearrange note taking page.
* 2.3.5. The system shall provide registered learners the ability to connect notes, annotate and tag them.
* 2.3.6. The system shall provide learners the ability to share their notes with others.

Only the 1.2.4 -> 1.3.4 change has been made.

**Comment by yilmaz-burak** [comment]
With this last change, we have completely updated our scenario acceptance criteria. So, closing the issue.
