### ISSUE TITLE
Class Diagram - User Service

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#104]
We have `User` class to hold information regarding a user's data; however, we need a controller class to manage users. In other words functionalities like registering, logging in, resetting passwords cannot be in the User class. 

## Fields
| Field| Type | Description|
| ---| ---| ---| 

## Methods
| Method| Args | Return |  Description|
| ---| ---| ---| ---| 
|register |user_name:string, user_mail:string, password:string| user_id: UID | Creates a new user with the given input. Also responsible for sending the confirmation mail|
|login |email: string, password:string| bool | Attempts to log in with the given email and password. If given input is valid, returns a token for user to use in the following request. |
|loginByGoogleAcc|googleAccount: Map<string, string>| bool | Attempts to log in with the given email and password. If given input is valid, returns a token for user to use in the following request. |
|resetPasswordMail |user_email: string | sent: bool | Sends a mail to provided email with a token to use with resetPassword function  |
|updatePassword |user_email: string, reset_token: Token , new_password: string| is_successful: bool |  Updates the password if the given reset_token is correct |
|banUser | user_id: UID, admin_token: string|  is_successful: bool| Admins can ban a user by takings their right to access to platform|
confirmEmail| user_email: string, confirmation_token:  string|  is_successful: bool | Confirm a mail by providing the token sent in confirmation mail|
|registerByGoogleAcc|googleAccount: Map<string, string>| is_successful: bool | Register to the platform by providing a Google account|

**Comment by ersoykadir** [comment]
| Method| Args | Return |  Description|
| ---| ---| ---| ---| 
|createToken|tokenType:int, user_id:UID| void | Creates a new token to be used in email confirmation or password reset|
|tokenComparison|token_db:Token,token_user:Token| bool| Compares the tokens came from user and database|

**Comment by muhammetssen** [comment]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/15876225/161963540-285edfc0-e346-43df-a360-c42cfdda497b.png">

**Comment by muhammetssen** [comment]
@ersoykadir and I presented the `UserService` class and team reviewed  the design in [meeting on April 5](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%238-05.04.2022#discussion-notes).

**Comment by salimtirit** [comment]
After reviewing for sequence digram of login I realized that we had missed a small thing. The user needs to Log-In via their google account. This is shown in the use case diagram, but there is no method here. Please add this method.

**Comment by ersoykadir** [comment]
Log-In via google account function is added.
