### ISSUE TITLE
Use Case - Admin User

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#106]
According to our [meeting notes](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%237-04.04.2022), use case of "Admin user" shall be prepared.
Use case will encompass what the capabilities of the moderator user is and what they can do. This way, scope and permissions of the moderator will be understood. 
Items:
* [x] Banning users
* [x] Delete comment
* [x]  Delete content

Deadline: 05.04.2022 - 23.59

**Comment by yilmaz-burak** [comment]
* We should decide whether it is `moderator` or `admin`
* Also, need to explain what `ban` means in the requirements.

**Comment by ersoykadir** [comment]
Reviewed at team meeting. Ban will be defined at glossary.

**Comment by yilmaz-burak** [comment]
Requirements that are covered by this diagram:
1.4.1. Admins shall be able to ban users for inconvenient behaviours.
1.4.2. Admins shall be able to delete inconvenient comments and articles.
