### ISSUE TITLE
Sequence Diagram: Creating Event

### ISSUE THREAD

**Issue by nurlandadashov02** [bounswe/bounswe2022group3#109]
The sequence diagram for creating events will be created with the help of the related classes.

- User wants to create an event for some course
- First we check if user is lecturer of the course
- if he/she is, then create the event
- add created event to the events list of a course
- if event is private notify the invited participants

| Actors| Classes | External Resources|
|---|---|---|
|Registered User| AuthorizationService| database |  
| | NotificationService| |
| | Event| |
| | Course| |

**Deadline for the first draft**: 05.04.2022 @21:00
**Deadline for final version**: 06.04.2022 @15:00

**Comment by nurlandadashov02** [comment]
First draft of sequence diagram for creating an event is ready and needs to be reviewed.
![test](https://user-images.githubusercontent.com/45170430/161819905-333bc7a0-9c29-4769-8f05-2db3a190f49a.png)

**Comment by muhammetssen** [comment]
Your work is a great example for sequence diagram. It is very clear and self explanatory. I have a few points to discuss:
- [AuthorizationService](https://github.com/bounswe/bounswe2022group3/issues/94#issuecomment-1088788902) does not have a method as grantCheck(id: UID)-> bool. The service is not well defined and further discussion and design needed to have a proper authorization mechanism. For now, we can use the `checkAuth(token: Token,class: Enum, id: UID) -> int` method for this case. You can call it by `checkAuth(token: token,class: Classes.Course , id: course_id) -> int`. 
I am not a fan of this design and will bring this up in our meeting this evening.
- We do not have a NotificationService :( Adding this to the meeting agenda too.

**Comment by nurlandadashov02** [comment]
Made some changes after receiving feedback from team members. Will be reviewed in the next team meeting.

![image (5)](https://user-images.githubusercontent.com/45170430/162631705-69a11d09-6d45-4f63-ab59-50561b4dfdaf.png)

**Comment by muhammetssen** [comment]
We have reviewed the final diagram with the team.
