### ISSUE TITLE
Sequence Diagram - Create Course

### ISSUE THREAD

**Issue by arfakbaba** [bounswe/bounswe2022group3#112]
As stated in [meeting 6](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%236-01.04.2022) The squence diagram for use case #83 will be drawn with the help of the related classes methods and user.

- User wants to make a create course ,
- After succes of create course, user add course ,
- After succes of add course, course added user's course list.

| Actors| Classes | External Resources|
|---|---|---|
| User| Course| Coursedb|  
| | User| | |

**Comment by arfakbaba** [comment]
First draft: 
![image](https://user-images.githubusercontent.com/66492431/162589846-162ccb9a-677a-45cb-805b-a6b79d90ae65.png)

**Comment by yilmaz-burak** [comment]
2nd activation-deactivation should be on db. Also OK response should come from the DB, not the class itself.

**Comment by arfakbaba** [comment]
Requried changes discussed in the  team meeting are made. The new diagram is below.
![image](https://user-images.githubusercontent.com/66492431/162924894-a461a773-cab7-4af6-946e-2a8f9d9f0c24.png)

**Comment by arfakbaba** [comment]
After customer meetings, some changes applied. The new diagram is :


![image](https://user-images.githubusercontent.com/66492431/163386557-cc06f662-51ec-4c1a-9030-a1f034903189.png)

**Comment by ersoykadir** [comment]
Looks good, complies with the latest conventions.
