### ISSUE TITLE
Documenting Meeting Notes Week #5 05.04.2022

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#115]
We had a sweeping meeting on 05.04.2022. It was focused on the things that we couldn't discuss in [previous meeting](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%237-04.04.2022) about the use case and class diagrams we designed and the sequence diagrams that we are going to design. 

You can find the meeting notes [here](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%238-05.04.2022)

 

- [x] Create the page and add a link for it to the sidebar and wiki page
- [x] Meeting details - date, participants - location
- [x] Agenda
- [x] Discussion Notes
- [x] Action Items

Deadline: 06.04.2022

**Comment by hsuleerkul** [comment]
LGTM! Thank you, no further review is needed.
