### ISSUE TITLE
Sequence Diagram: Poll Actions

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#117]
Sequence diagram for use case [#66](https://github.com/bounswe/bounswe2022group3/issues/66) will be created with the relevant class diagram.

* User will create a poll.
* User will view poll results.
* User will delete the poll.

| Actors| Classes | External Resources|
|---|---|---|
| User | User | Database |
| | Poll | | 
| | Course | | 

Deadline: 09.04.2022, 23.59

**Comment by yilmaz-burak** [comment]
I think no class functions should return a void type value. This makes acknowledgement logic hard to implement. Will be discussed in the meeting.

**Comment by yilmaz-burak** [comment]
Initial draft has been implemented. Can be found [here](http://www.plantuml.com/plantuml/umla/PP2_JiGm3CRtF8N7E-buWGxe9610W61XHcvjeeWcgMmNNf-ulUfKNHV__trV4yvgA3RdCU1WLM3zNckCJC_bKra05UOMmuHYQKWJ5eEFEeu-c5hS3Puofb5PVjF0li1P0w5XZyfEVhpcFgO-X11dLhkx1-7OmI2Cniu_kEfNmSoTcgGIJql31RR6XAf_LUXI7qD3DD02xE3zPQqvQmVAXHvg-KwIqL8jRmrps0CTq7PN9tw-TnRPBW2ccykJrHykcm7gjnzPNh0A8D71ysEW7guADuRFN6ZEupy0).
![image](https://user-images.githubusercontent.com/46003469/162577985-d4442d0c-ceb6-47a7-8c46-532864684e6a.png)

**Comment by yilmaz-burak** [comment]
Meeting notes: Give class names as is. Migrate createPoll to Course class.

**Comment by yilmaz-burak** [comment]
## [Create Poll](http://www.plantuml.com/plantuml/umla/RP6_JiGm38VtF4N6Gm8UW06T10m82H1_vfCRUuYKNgiuvVcncy7jdRl4bQtlzyKvSeFQbh44I6sgiN-_J3K2nqNE46QPo2dFS6xnQLega_RIMgK2pBk9pwaKxSzozYv2Wm6ObFoyrfs0GmX18-BTunON7sAg18qKTUYDKyRR5NcIB1YfKUKRTSv_ChYJsTG2Deyzzeg5vD8imovaIE7Z8E3Nz--Nhv-3airABuZ3fSF7spPATs2ywqKeyNvrpHYG71dVsduSIKCwiiRnTI_8-dwUfoDrf3CkO_a7)
![image](https://user-images.githubusercontent.com/46003469/162632053-a3182a9c-fbd1-4c3b-8f8c-4c21515c764a.png)

## [Get Poll Results](http://www.plantuml.com/plantuml/umla/PP2zhi8m38NtF4N6UmTu00PK2Ren87xcogcjAb98gzWjhuyjG2tGnLNoVJv7gLYWo7XB3bhfYtz-LwRYWVseqmqAn3OEaCKV-vJiOj3P9c1s2081c4pRl_-LmE2SwNwrdMc_yHt9YNXCmdzst4Jyj-WuWT1YxQoeZq75StseTvTVoP8mVCTOKOUqW3vNMhKNjkxYHBc1p7Sgl9JcEXLbr4Tw0000)
![image](https://user-images.githubusercontent.com/46003469/162632162-d58acc75-e46d-499b-8bc3-bd21b5c5a072.png)

## [Delete Poll](http://www.plantuml.com/plantuml/umla/PP0n3i8m34Ltdy8Z35o00NLe9v1WW1avjOT8eQrgb_DZgqWjD8kZvBt_erHgDDhqAa2jzIFEww4o8YbEFc5m8BTveCxmrfSI5uFFjf0gC1abKWcj_kw3u0GGEXvE2ur7P2bY4ZcxE7vctaTrVfF9AdPHtEVaOjrScdkpbQA9qt_DzGmiQ-GtCLusKu5jwolfs3_b0m00)
![image](https://user-images.githubusercontent.com/46003469/162632101-55b07f53-dfd5-4111-8e27-338bd8ee2ac5.png)

**Comment by yilmaz-burak** [comment]
Relevant changes discussed in the meeting are made. Will be checked again in the next meeting.

**Comment by yilmaz-burak** [comment]
Notes: Return arrows should be dashed, return types should be given.

**Comment by muhammetssen** [comment]
Having two different insert operations is not very clear. One of them should be appending to a list in the course object.

**Comment by yilmaz-burak** [comment]
Made necessary changes accordinng to customer feedback.

## [Create a Poll](http://www.plantuml.com/plantuml/umla/RPBFIWGn38VlVOhSL71zW3t8WdeGGSK_voNJHgZCJ8Scu_ERPWOwkzrUMaZwvVUL7bWmoppq3hsa3ClwPig03BFkpatQ4NsSS1HuI7DcAZLl9zyZyqd7U-hxKfzqNwe11JjaAkH7Eo-4q3ddoWZOtMzni0UV2OKAwdef76EuDUHHP-50GfblIkRufuqdOROa1LkE5jkm0bsarHbLg2AL7pe5Fxz-FdrycVj-MXyWTR_afTvNNUtTdKLwUx79jSTjyUSFKoVScK0CThj9U5bbYsgILsG9ZoD4eG7Yk29MdIk6Fh90-h5ftEWrYHl1MZP1-sHcraWr1WSQW_xLVm00)
![image](https://user-images.githubusercontent.com/46003469/163438009-b6bfd51e-7a4d-4035-9c21-5d1c325e9603.png)

## [Get Poll Results](http://www.plantuml.com/plantuml/umla/VP0z3i8m34Rtd28Z3Eq1Eg1Aq8q1yJDNRcDLaK9QnMwvFZO8fJ2G8Oxaz-nFgOaXyNmF1deUatsV6s6oG7QMQYO1VEydY6nFOmZQcAJs0OYC0uOE25KxVDv2kCuOrMsnoxIjx81yHfe3qqQ7LQzcgLVhtLPJ-0KOLnkoBQDS9pCkpR7PN__xib_OucTxLep3DPiXLJJu5rqEVi7OGgG79bgxEMUDqSb7FW40)
![image](https://user-images.githubusercontent.com/46003469/163438470-17e4e783-6575-4e08-97d7-43647340e6c9.png)

## [Delete Poll](http://www.plantuml.com/plantuml/umla/VP2z3e903CVtUugEEk03C1W6c3JHGMTJQ8TBJY2q-Fos4dCN1nbQalx-7xb651TTdodWeDC2stSNNW05LjjXDY0ESSPHuJgbv8VPzf1G910gzYZiilRxRmJr8RWSgcEceGRYnChki_DHVuu77uz8UsyHNwXS96IrML5l7crtxcxTVxtb6rlzf5zEWRXaIdTZlV66PQxiql18zbXl)
![image](https://user-images.githubusercontent.com/46003469/163438787-3600870e-09f5-4555-8700-af4322221ce1.png)

**Comment by nurlandadashov02** [comment]
Reviewed, necessary corrections have been made.
