### ISSUE TITLE
Sequence Diagram: Admin Actions

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#118]
Sequence diagram for use case [#106](https://github.com/bounswe/bounswe2022group3/issues/106) will be created with the relevant class diagram.

* Admin will ban any user.
* Admin will delete any comment.
* Admin will delete any content.

| Actors| Classes | External Resources|
|---|---|---|
| Admin User | UserService | Database |  
| | Comment | |
| | CourseContent | |

Deadline: 09.04.2022, 23.59

**Comment by yilmaz-burak** [comment]
* For the banning actions, we should implement banning function in user service.
* User class should have is_banned field also, since banning is different than deleting.

**Comment by yilmaz-burak** [comment]
* CourseContent class should have a delete function, will be discussed in the meeting.

**Comment by yilmaz-burak** [comment]
First draft can be found [here](http://www.plantuml.com/plantuml/umla/ZP51JiGm34NtEKMMPS45MA0PjLqWa422EO2RU16fSKUDE-SdfWKvM49qbT_-x_pddWh3obkU7GHULhy_vvWJUIWUvE2krP92kWAnlnHStt6zfO1YsAeiksni_P8p4lSpb2A-iEiW-fTngmFwXRYr4t_RlOl0C451gJOSPt75oJdugdh_g9lu1py1ITDEtZx5Ew5BDs1i2gkpJ8XJ3LxUXlF7Q79oLvpiFQ_FBg8sjJFt1IgVBQ4Gz99g9kACZCSck-EZBjLkLOiVd65y6IkE3XkY9cYHp633PBgqKCGMIl_rBcZL0ggmqy82sX46a_XlJEB_O18hp1DItFBy2G00).

![image](https://user-images.githubusercontent.com/46003469/162579610-692aac9f-8aab-42be-b45c-266c462e36d2.png)

**Comment by yilmaz-burak** [comment]
Finalized Version:
Since conventions and seperation of the use cases were all the critiques, closing the issue.

## [Banning a User](http://www.plantuml.com/plantuml/umla/PP2n3i8m34JtV8L76FW11jHAPM802JeZf_PWYOOgSVlzn4H8eSrqZkwUJswIOjHvV3aSz1sXl9P62O09q8IRiaK6cJ0ez8dZdUCY0vjXpcCgeoDKz9ZO2DrFPmzvv_1BF9pg01p1Op3WpdwVGdjh8Gig_u4hRGZoETdVklPntWPj6_djfkl54TUc5RGKNFlg5Wq7oeVw0000)
![image](https://user-images.githubusercontent.com/46003469/162631605-c3ff3187-2733-4d00-b4fa-b7e58eb44427.png)



## [Deleting a Comment](http://www.plantuml.com/plantuml/umla/ROwn3i8m34HtVuL76FW11bH4Eu74mewSs4Ea9AqQb--dfXr8LKyd-UxTDKLfr2b58A_zYCjTEOMCL91Cm31RWWy3PSLRdv9ajQTVf8zK2Z0fEIfYyNRLPc87G3_SwL8by8miKLHMuc5zlWCVRKpua4hTKSLd7BiPqdQFxjNjfgsStKxnymui_wujULcyDLPZ6iayfVW5)
![image](https://user-images.githubusercontent.com/46003469/162631619-1d8c7ffd-1317-4dbb-89f4-9fbe24b0f8dc.png)




## [Delete Course Content](http://www.plantuml.com/plantuml/umla/VP2nhi8m34LtVuN7zmP-W04LjPr0Oc57JkmXKfjMjSltKrE6fa9akfQEZsvSgT5aSzy1HHicND-P-vIH5Ca3Z0kIOXef6zR3FAdKGpR9vaXSO-n85O79A92AMvfFTee30BsjXrEvSaIMJamAyL_SJe_4_zulFScas8Rju6eEYx1fh-sz_U7mEXo-LBbTW6LBxVth7_PWKQcIpCj1Nm00)
![image](https://user-images.githubusercontent.com/46003469/162631634-64f9c24e-0f10-458b-aba7-6e7588aa9cd8.png)

**Comment by yilmaz-burak** [comment]
Return types should be given and return arrows should be dashed.

**Comment by nurlandadashov02** [comment]
Reviewed, necessary corrections have been made.
