### ISSUE TITLE
Document Non-functional requirements

### ISSUE THREAD

**Issue by nurlandadashov02** [bounswe/bounswe2022group3#12]
No-functional requirements shall be identified from the project description. A draft for these requirements will be documented on the [requirements page](https://github.com/bounswe/bounswe2022group3/wiki/Requirements).

Reviewer: @hsuleerkul 
Deadline: 16.03.22

**Comment by nurlandadashov02** [comment]
Non-functional requirements have been examined and classified. The requirements were documented on the [Requirements wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Requirements#non-functional-requirements). They should be confirmed with the team.

**Comment by nurlandadashov02** [comment]
Non-functional requirements have been reviewed and approved by the team. 
https://github.com/bounswe/bounswe2022group3/wiki/Requirements#non-functional-requirements

**Comment by hsuleerkul** [comment]
Closing this issue as both I and the team reviewed the content. [Content Link](https://github.com/bounswe/bounswe2022group3/wiki/Requirements#non-functional-requirements)
