### ISSUE TITLE
Reviewing Use Case Diagram Relations

### ISSUE THREAD

**Issue by Brunettow** [bounswe/bounswe2022group3#121]
This issue is aimed to detect the use case diagram deficiencies. Everybody in the team is expected to review their use case diagram especially by means of their diagram relations. 

- [x] Arif Akbaba
- [x] Bilal Aytekin
- [x] Mehmet Gökberk Arslan
- [x] Nurlan Dadashov
- [x] Hatice Şule Erkul
- [x] Kadir Ersoy
- [x] Ahmet Kudu
- [x] Muhammet Şen
- [x] Bengisu Takkin
- [x] Burak Yılmaz
- [x] Salim Kemal Tirit
- [x] Mertcan Özkan

Reviewer: @Brunettow 
Deadline: 11.04.2022, 21.00

**Comment by nurlandadashov02** [comment]
Use case diagram has been finalized.
