### ISSUE TITLE
Sequence Diagram : Login / Sign in

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#124]
### Task:
The sequence diagram for the use case [Login / Sign in](https://github.com/bounswe/bounswe2022group3/issues/91) will be created with the help of related class diagrams. 

What will happen?

- User will make a login request with their e-mail and password.
- System will check the correctness of this information.
- System will let the user in if the information is correct.

|Actors|Classes|External Resources|
|---|---|---|
| Registered User | UserService | database| 
| --- | EmailService | --- |

**Comment by salimtirit** [comment]
![image](https://user-images.githubusercontent.com/64011660/162619732-a27f3460-2777-440f-b39d-68c99386931a.png)

![image](https://user-images.githubusercontent.com/64011660/162619792-cdbdf7b0-1534-45e7-a266-6a5fa47910ad.png)

![image](https://user-images.githubusercontent.com/64011660/162619796-45d922c3-ebe2-4d07-9dce-e68b957cfbda.png)

**Comment by salimtirit** [comment]
The first draft of the login with email part is up.
![image](https://user-images.githubusercontent.com/64011660/162635476-821417e9-e76f-4611-a293-33c79b6477df.png)

**Comment by salimtirit** [comment]
Some minor changes due to customer meeting in 13.04
![image](https://user-images.githubusercontent.com/64011660/163340378-1eda3914-bb44-4506-9450-d2beb05ada91.png)

**Comment by salimtirit** [comment]
Login with google account case first draft
![image](https://user-images.githubusercontent.com/64011660/163349506-c888b7be-ffbc-49cf-bd6a-8db38a2e67d1.png)

**Comment by salimtirit** [comment]
In Login With Google Sequence:
- token_db removed since we no longer have auth service. 
- Added details to Select statement.
![image](https://user-images.githubusercontent.com/64011660/163355155-de6786ba-889d-4832-b8d2-0ddf0b40e301.png)

In Login With Email and Password Sequence:
- token_db removed since we no longer have auth service. 
- Select statement changed to Select User
- failed login count statements changed to user.failed_login_count 
![image](https://user-images.githubusercontent.com/64011660/163356428-fac58252-6970-4444-b6f2-bc3ab9d950f2.png)

**Comment by muhammetssen** [comment]
Thanks for the updates. \
I could not understand the variable names in login with google diagram. What is the responsibility of`getInfo` function? What information dont we have in `googleAccount`  variable so that we make another function call with Google API?

**Comment by salimtirit** [comment]
Thank you for your attention. It seems unnecessary for me too. I deleted `getInfo` parts. I also changed the select statement. This is the last version now.
![image](https://user-images.githubusercontent.com/64011660/163470272-75503dcd-4f70-4fdc-97be-53ab95b77773.png)

**Comment by salimtirit** [comment]
reviewed with the team looks good
