### ISSUE TITLE
Sequence Diagram - Create Content

### ISSUE THREAD

**Issue by Brunettow** [bounswe/bounswe2022group3#125]
Sequence diagram for use case [#75](https://github.com/bounswe/bounswe2022group3/issues/75) will be created with the relevant class diagram.

* User will create a Chapter.
* User will add content to a chapter.
* User will delete the chapter.

| Actors| Classes | External Resources|
|---|---|---|
| User | Course | Database |
| | CourseContent | | 
 | | Chapter| | 
 | |Badge | |

Deadline: 11.04.2022, 21.00

**Comment by Brunettow** [comment]
[PlantUML Link](//www.plantuml.com/plantuml/png/NL71Je0m3BttAvfmmGD-m0u6HMECHXCrNarX3Io1ORRYzplT5XjwuVMrx_4eVHGAScmhq2Hxm5pN2bF4ln6KZUuAX_q8aT4WMJiiz2KSsYa_FvqrMBZBV-xYL-o-IRYAcoStBt8Vc3r0vf9rbQAfgFMqSMgZ1ETdvLCtiz7DUZ1aIaKqM2AOCWBBPmC0Iq8ZHSPKjmfJH3kgSAb3Wm_FRtUlx_LxLQ0qnUR3xIiB9DpfGxqygZUVNFDPQrHzDQt9-m0zUvj-rmy0l)

![image](https://user-images.githubusercontent.com/63921045/162628435-5454af9c-9152-4885-8290-ec72848aab81.png)


[PlantUML Link](//www.plantuml.com/plantuml/png/VLBDJiCm3BxdAIBrKYJW0N90Oss59YP0R715QMrr4QMTKfVdfoO1HrgtN9Pz_NwSJrwDP3rDNvso3GrUXtEVtEseVp-foBYvqyKm-H6rqIrISR17GfytuVV3WT4HknNiYiNksnB-YREjQm_qu15xfS2IhUsCbl72gL2hmEL8gEUuNRMjYdqIDMDlcrBCcPQzkFvJGIs36XqL9Wwc04yLILXuw4LP82UT10whBC3QGeivEUgufP6ywzjh3JWstXt93Vq_cXOJ7K8pwsv25I7sPqisIwpDWh4viGt2xDqD7P9I_5SQtJpjgjTzNZDuhiOa_FbnkRfeAZK8Tt4AUPYq7GINsf0rcKyfzxWiA-nXNkGV)
![image](https://user-images.githubusercontent.com/63921045/162628667-59833c5e-0ab8-4219-a23a-4f752412349e.png)

**Comment by nurlandadashov02** [comment]
Completed.
