### ISSUE TITLE
Reviewing class diagram relations and correcting them

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#126]
Class diagrams of our project is almost finalized. We need to handle the relations of classes with each other, review them and add new ones if necessary. 
- Review each class diagram content, check its relations with other classes.
- Some of the relations are missing, stated in the TA customer meeting add them and present all to the team.

Deadline: 11.04.2022 20:30
Review Deadline: 13.04.2022 17:00

**Comment by bilalcim** [comment]
As per the TA advised, I have connected the ``SearchService`` and the ``User`` classes with a bold headed arrow from ``SearchService`` to ``User`` because the prior sends a synchronous message to the latter. The arrow is labeled "serves".

**Comment by ersoykadir** [comment]
Team reviewed the relations and also TA took a look, they are sufficient and done for now.
