### ISSUE TITLE
Use Case Diagram - Follow/Block User

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#127]
### Task: 
As stated in [Meeting Notes #9 09.04.2022](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%239-09.04.2022), use case diagrams are missing follow and block user cases.
What we need to cover:
* Follow a user,
* Block a user, restricting someones view from user's personal information.

**Deadline:** 11.04.2022 20:00

**Comment by ersoykadir** [comment]
![image](https://user-images.githubusercontent.com/49765256/162628252-bb0f3dfb-1a7d-4980-be05-448477bfc8de.png)

**Comment by muhammetssen** [comment]
Thanks!
