### ISSUE TITLE
Document search engine requirements

### ISSUE THREAD

**Issue by bilalcim** [bounswe/bounswe2022group3#13]
A draft for the requirements in the project description which concerns the search engine functionality shall be summarized on the
[requirements page](https://github.com/bounswe/bounswe2022group3/wiki/Requirements).  

Reviewer: @nurlandadashov02
Deadline: 16.03.2022

**Comment by bilalcim** [comment]
The search engine requirements are documented and awaits review.

**Comment by bilalcim** [comment]
The draft for the search engine requirements is split into system and user requirements, and documented in Requirements, section 1.5 and 2.5.

**Comment by nurlandadashov02** [comment]
Search Engine requirements have been reviewed.
https://github.com/bounswe/bounswe2022group3/wiki/Requirements#14-search-engine
https://github.com/bounswe/bounswe2022group3/wiki/Requirements#25-search-engine
