### ISSUE TITLE
Tracking statuses of Sequence Diagrams

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#131]
We have prepared sequence diagrams for different aspects of the project. Every sequence diagram has its own issue; however, we need a single table to see the current status of each issue.

| Name | Issue | Status |
| --- | --- | ---|
|Modifying Custom Badges | #101 | completed |
| Create Discussion Forum | #102 | completed |
| Search & Filter | #105 | completed |
| Registration/Sign-up | #107 | completed|
| Creating Event | #109 | completed |
| Create Course| #112 | completed  |
| Enrolling a Course | #116 | completed |
| Poll Actions | #117 | completed |
| Admin Actions | #118 | completed |
| Managing Notes | #119 | completed |
| Editing Profile Page | #120 | completed |
| Login / Sign in | #124 | completed  |
| Create Content | #125 | completed |
| View Course Content | #129 | completed |

**Comment by nurlandadashov02** [comment]
All sequence diagrams have been completed.
