### ISSUE TITLE
Writing an Evaluation of Tools Used

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#135]
### Task:
As stated in issue #132 I need to write the evaluation of the tools we have used to manage our team project. This evaluation will be used in milestone one.
I will evaluate the following platforms:

- [x] Github
- [x] Lucid app
- [x] Draw.io
- [x] PlantUML
- [x] ProjectLibre
- [x] VS Code Markdown PDF
- [x] Slack 
- [x] Whatsapp
- [x] Zoom
- [x] Google Docs

### Required Tools:
VS Code Markdown PDF

### Place To Put The Documentation:
Milestone 1 Report (After its done there will be a link here)

### Deadline: 
14.04.2022 20.00

**Comment by salimtirit** [comment]
### [Github](https://github.com/)
Github is the main platform we used in our project. Basically, we did everything and put everything on Github. We documented our requirements, questions, communication plan, meeting notes, personal efforts, user scenarios and mockups, and UML diagrams on Github. In the meetings, after discussing the meeting agenda and deciding who will do what we wanted everyone to open a related issue for that task. We have used the issue system to track our progress. It increased our collaboration since we could comment on issues. We have used the markdown feature of GitHub exclusively in our issues and wiki pages. We used it to create checkboxes for subtasks of an issue, links to connect relevant pages, tables to show things in an ordered fashion, headers to create titles for the parts, bulleted or numbered lists to create lists, and bold, italic, emphasis features to emphasize some words. We haven’t used the code part of Github yet since we didn't do any implementation but the version control system part helped us to track the differences between edits of a page. We also used the sidebar of GitHub to keep our wiki page organized. We used [README](https://github.com/bounswe/bounswe2022group3/blob/master/README.md) to create a nice page to introduce ourselves and the project.

**Comment by salimtirit** [comment]
I realized I need to add Google Docs to the list of tools so I added it.

**Comment by salimtirit** [comment]
### [Lucid.app](https://lucid.app/)
We used the lucid app to draw our diagrams. It allows us to work together on the same document. For example in the class diagrams everybody created the given class in the same document then we ordered them together in a zoom meeting. For the use case diagram, we build it part by part in the same graph and reviewed it in a meeting. It shows who is doing changes currently in the document but it doesn't show the information from the past. It can be tiring to try to find the owner of a change. Other than that it provides a solid, collaborative environment with many beautiful options of shapes. It is easy to use, moving objects and connecting them with arrows is pretty easy.

**Comment by salimtirit** [comment]
### [Draw.io](https://app.diagrams.net/)
We used draw.io to create our mockups. First, we wanted two of our friends to create a base for web and mobile mockups. They created two beautiful templates and shared them with us. After that, every group created one mockup for web and one mockup for mobile. It is easy to use and has many options. Exporting as a png option is very useful. You can export without a background and as a single file. We used this feature in some of our mockups.

**Comment by salimtirit** [comment]
### [PlantUML](https://plantuml.com/)
Some of us used plantUML to create sequence diagrams. It takes care of the drawing part itself and it is closer to coding. It creates arrows, “alt” or “for” boxes in a structured fashion. It creates the actors, participants, and database automatically. It is also symmetric about these one on the top and one on the bottom.  It can also be used to create other types of diagrams but it is easier to do them with lucid app

**Comment by salimtirit** [comment]
### [VS Code Markdown PDF](https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf)
This is a tool that we have used during the preparation of this document. Since we all got used to the markdown feature of Github we decided that we can write this document in Github under relevant issues and then connect it in a single PDF file. This tool can embed links, create tables, show emphasizes, and even create plantUML diagrams inside the pdf. It is very useful and can be used inside vs code. It can export in pdf, html, png, and jpeg formats.

**Comment by salimtirit** [comment]
### [Slack](https://slack.com/)
We used slack as a platform to communicate with our friends and teachers about the project. We asked questions and checked the answers. We created a separate workspace for our group only. We used it to communicate between the group members, share helpful links, and bring together questions. Inside this workspace, we created groups when we needed them. For example, we created three groups for the user scenarios and mockups. Creating different text channels helped us increase our productivity since we could easily follow multiple topics at a time.

**Comment by salimtirit** [comment]
### [WhatsApp](https://www.whatsapp.com/)
We used WhatsApp to communicate instantly and discuss small things. Since we all are used to checking WhatsApp frequently it helped us communicate. WhatsApp is generally hard to track so we didn’t use it for very important subjects that need to be checked by all team members. Generally, when we needed help or were not sure about a subject we used WhatsApp. We also used it for general chit-chat from time to time.

**Comment by salimtirit** [comment]
### [Zoom](https://zoom.us/)
We used zoom for weekly meetings and other additional meetings. The problem with the zoom is that since there is a time limit to the free version of the zoom our meetings got interrupted. But we used this issue to our advantage and counted zoom sessions to track the time and gave breaks after two or three zoom sessions. We shared our screens when we needed them and used the chat feature to share some links.

**Comment by salimtirit** [comment]
### [Google Docs](https://docs.google.com/)
We used Google Docs when we needed to collaborate on something written. We used it to create our RAM. One of our friends created a template and another one filled the work part. Then everyone selected their own role in a work so the job is done more easily. It is free to use and like the online version of MS office so everyone is used to using it. Since it stores documents in Google Drive it is hard to lose a document.

**Comment by salimtirit** [comment]
### [ProjectLibre](https://www.projectlibre.com/)
We used project libre to prepare our project plan. It is open-source, free software. It is a desktop application and it is stated that there will be a cloud version. Apparently, the cloud version is being waited for a long time. Since it is only available as a desktop application we could not efficiently work on it. It was not practical to share the screen on zoom and try to fill a table together. It is not stable on different operating systems. Some features work in windows, others in ubuntu, and others on macOS. It has no support for M1 so it works very slow on new MacBooks. It crashes from time to time so we had to start over four times. The user interface is not good. We didn’t like this program at all. It didn’t make our job easier than it is. It would have been easier to do the whole plan on Paint. This program should not be recommended to any user or any group in the future. We are very disappointed about this.

**Comment by hsuleerkul** [comment]
It is ready to be added to the Milestone report. Thanks a lot!
