### ISSUE TITLE
Writing the Evaluation of Responsibility Assignment Matrix (RAM)

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#136]
### Task:
As stated in issue #132, I will write an evaluation of our RAM. The topics I will focus on are: 
- The labels we use in it
- How we decided to add which tasks to add in the matrix
- How we tracked it

### Place To Put The Documentation:
Milestone 1 Report (After its done there will be a link here)

### Deadline: 
14.04.2022 20.00

**Comment by hsuleerkul** [comment]
### Evaluation of RAM
In the Responsibility Assignment Matrix, one can clearly see who did what task and who helped them, reviewed the work and so on. The tasks in the RAM are the tasks we have done in the current versions of deliverables. We did not include any tasks that are completed but removed from the deliverables for one reason or another. There are labels for describing how a teammate contributed for the tasks. They are : Lead (L), Secondary (S), Contributor (C), Reviewer (R), and finally None (N). Leading a task means that a team member either does the job (with or without other team members), or he/she tracks how it's done and/or when it is done. Secondary label means a team member helped lead of the task with the task, and he/she made same effort with the lead. Contributor of a task means some parts were done by the contributor however it was less compared to the lead, or it can mean a task is shared between all the team members and everyone has almost same workload. Reviewers are the team members checking the outcome of the task after it is done. None label is used when a team member was not involved in a task at all. In our resulting RAM, we have a lead for all the tasks we have done so far except the research tasks. For requirements, class diagrams, use case diagrams and sequence diagrams, we reviewed them in the group meetings, because of that, we all have review label under our names in those task categories. Filling in the matrix, showed us how we worked until now in a more structured way.

**Comment by ersoykadir** [comment]
Other than small adjustments done below for punctuation and pro-nouns, it explains the RAM creation process very well.
> In the Responsibility Assignment Matrix, one can clearly see who did what task and who helped them, reviewed the work and so on. The tasks in the RAM are the tasks we have done for the current version of deliverables. We did not include any tasks that are completed but removed from the deliverables for one reason or another. There are labels for describing how a teammate contributed for the tasks. They are : Lead (L), Secondary (S), Contributor (C), Reviewer (R), and finally None (N). Leading a task means that a team member either does the job (with or without other team members), or he/she tracks how it's done and/or when it is done. Secondary label means a team member helped the lead of the task, and he/she made same effort with the lead. Contributor of a task means some parts were done by the contributor however it was less compared to the lead, or it can mean a task is shared between all the team members and everyone has almost the same workload. Reviewers are the team members checking the outcome of the task after it is done. None label is used when a team member was not involved in a task at all. In our resulting RAM, we have a lead for all the tasks we have done so far, except the research tasks. For requirements, class diagrams, use case diagrams and sequence diagrams, we reviewed them in the group meetings, because of that, we all have review label under our names in those task categories. Filling in the matrix showed us how we worked until now in a more structured way.

**Comment by hsuleerkul** [comment]
Thanks for the feedback!

**Comment by hsuleerkul** [comment]
We added the version @ersoykadir has edited to the report
