### ISSUE TITLE
Writing the Evaluation of Project Plan

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#138]
### Task:
As stated in issue #132 :  This evaluation will be written on Project Plan, reviewing its creation process.
### Place To Put The Documentation:
Milestone 1 Report (After its done there will be a link here)

### Deadline: 
14.04.2022 20.00

**Comment by ersoykadir** [comment]
## Project Plan
The baseline of project plan mainly depends on the RAM, responsibility assignment matrix. We decided to prepare the RAM(#134) before the project plan so that we can extract the tasks done during the whole project process. After that the tasks has been decided at the RAM table, we constructed the project plan upon those tasks using projectLibre(`#projectplanissue`). Essentially, looking through github issues related to RAM tasks, project plan has been prepared by inserting the assignee, start time and end time data of the issues into projectLibre.

**Comment by hsuleerkul** [comment]
Thank you! It is ready to be added to the Milestone report.
