### ISSUE TITLE
Write an Evaluation of Scenarios & Mockups

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2022group3#139]
### Task: 
Explain [user scenarios ](https://github.com/bounswe/bounswe2022group3/wiki/User-Scenarios-and-Mockups) which are stories created to show how users might act to achieve a goal in a system or environment. Also, move kindly all photos about those scenarios to the Milestone 1 Report. 
### Required tools (if applicable) or researches:
Pdf format
### Place to put the documentation:
Milestone 1 Report which is located on the side bar in Wiki
### Additional notes:
This is part of Milestone 1 Report.
### Deadline: 15.04.2022 - 23.59

**Comment by ahmetkudu** [comment]
The evaluation part is the following:

To demonstrate the platform's usability and globality, user scenarios should be real-life examples that everyone can appreciate. They should depict diverse types of individuals with varying desires. Event creation, creating discussion, and note taking are the three user scenarios we created. From the requirements, we were able to clearly identify the personal backgrounds of distinct users, what they desire, the preconditions, goals, and acceptance criteria for these situations. We were able to come up with new design and feature ideas for our platform by thinking about the activities step by step for the situations. This helped us come up with new design and feature ideas for our platform that would help users utilize the platform more efficiently. Mockups should be realistic, demonstrating the required features for various scenarios and displaying all user processes from the scenarios onward.

**Comment by ahmetkudu** [comment]
Scenarios and Mock-ups exported to [Scenarios and Mock-ups.pdf](https://github.com/bounswe/bounswe2022group3/files/8491987/Scenarios.and.Mock-ups.pdf)

**Comment by ersoykadir** [comment]
Looks good, explains the scenario and mockups process well.

**Comment by ersoykadir** [comment]
Reviewed by the team!
