### ISSUE TITLE
Update Communication Plan

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#14]
Update the communication plan with the additional meeting on Wednesday as discussed in the weekly zoom meeting.

**Comment by salimtirit** [comment]
Deadline: 12.03.2022 23.59

**Comment by salimtirit** [comment]
The communication plan is updated with the new meeting time and location. And also with the content of the meetings.

**Comment by salimtirit** [comment]
This issue needed approval from the reviewer. Sorry for closing before the review.

**Comment by yilmaz-burak** [comment]
Wednesday change seems to be added. Closing now. Thanks!
