### ISSUE TITLE
Writing Executive Summary 

### ISSUE THREAD

**Issue by arfakbaba** [bounswe/bounswe2022group3#140]
### Task:
As stated in issue #132 I will write the executive summary . Executive summary includes three parts:
Prject description indicates which area the project belongs to, what features it has and the structure of the project.
Project Status is a brief summary of what has been done for the project so far.
Forward Plans  is a brief summary of what should be done for the project after this stage and what decisions should be made for future stages.

- [x] Project Description
- [x] Project Status
- [x] Forward Plans

### Place To Put The Documentation:
Milestone 1 Report 

### Deadline: 
14.04.2022 20.00

**Comment by arfakbaba** [comment]
### First draft of Executive Summary
1.1	 Project description
This project is a online learning platform which can offer such environments independent of the location of the teachers and learners. There are two types of user in our platform, which are lecturer and learner. Lecturer imply anyone who knows something well and can teach it and learner is anyone who is interested in learning. This departs from the classical educational course room context. 
Learner users can enroll in a learning experience where s/he will utilize resources and solve problems. They can monitor their progress their enrolled course.  They can create notes related to what they are learning  and share notes with others. They can also connect notes, annotate and tag them. 
Lecturer can create a course and decide to its content. Lecturers  can organize in-person meetings by specifying locations, dates, duration, and other relevant information using the platform. Lecturers can also  create polls to help the students contribute to some decisions taken during the lecture. Polls can be in three options: anonymous mode, multiple answers, and quiz mode. Lecturer can also have reputations based on the feedback gathered by the learners as they learn.
This platform provides users to create their own a profile that describes their interest and their knowledge. Users be able to follow other users and be able to see the activities/achievements of those they follow in this platform. This platform offer semantic searching, browsing, and recommendations to offer a rich learning environment. The system of this platform make recommendations Based on the learning experience
This platform supports Android, and Web so that it is available on both mobile and the web. We also take into consideration ethical concerns while designing our platform. Therefore, we follow the rules of KVKK and GDPR and the standards of W3C as a software project.

1.2	 Project Status

At the beginning of course, we are not experienced about design issues. At first, we all discussed about tasks and made a joint decision. Afterwards we divided each task into sub-tasks and tried to give responsibility to every member of team. Each Friday we have regular meetings. We talk about current assignments about our project what we will do next week and how to distribute the given tasks. We assign each task to someone and decide about  a deadline for each task. Everyone comes forward for every task and does the tasks before the deadline.
First we need to be in contact every time, so we focus on communication and create communication plan, create groups on different communication platforms in first team meeting. Then we focus on our project and decided about the requirements. We created mock-ups and scenarios. We made customer meeting and rearranged requirements considering the customer’s wishes. Then we focus on mainly on design and create use case diagram, class diagram, sequence diagram. 

1.3  Forward Plans
We have created a guideline to help us implement the project until now.  We will decide about our project plan to know the time a task will be finished. We will start the implementation of the app. We need to decide which team members will develop frontend, backend and mobil application. We are going to discuss about the tools and frameworks, which might be useful for us. We need to find out which programming languages, services and APIs to use and conduct research and learning on those tools. We know that through the life time of project we will run across some obstacles. So, we will continue to arrange meetings frequently about those situations to ensure that everything is clear.

**Comment by hsuleerkul** [comment]
I have read your Executive Summary. Overall, you explained what we did and what we are going to do really well. However, I want to point out two things:
-In 1.1. the expressions learner users and lecturer user might be misunderstood. Right now we only have one type of regular users who can both be a lecturer and a learner for different courses. I suggest you to change `There are two types of users in our platform, which are lecturer and learner.` this sentence to `There are two types of users in our platform, one is an admin user and the other type of user can be a lecturer and a learner depending on the course.`. After that you can just explain what a user can do in our platform in a combined manner.
- I corrected some grammar mistakes I saw and my here is the revised version of 1.2. 
   At the beginning of course, we were not experienced about the design issues. At first, we all discussed about tasks and made joint decisions. Afterwards, we startted dividing each task into sub-tasks and tried to give responsibility to every member of the team. Each friday we have regular meetings. We talk about the assignments at the hand, the status of our project, what we will do next week, and how to distribute the given tasks. We assign each task to someone and decide about a deadline for each task. Everyone comes forward for every task and does the tasks before the deadline.
First, we created a communication plan because we need to be in contact all the time. In order to do that, we created groups on Whatsapp and Slack in the first team meeting. Then, we focused on our project and decided about the requirements. We created mock-ups and scenarios. We met with the customer and rearranged requirements considering the customer’s wishes. Then, we focused on mainly on design and created use case diagram, class diagram, sequence diagram.

**Comment by arfakbaba** [comment]
After rewiews, some grammmer mistakes and arrangements done.

### First draft of Executive Summary

-  1.1Project description
This project is an online learning platform which can offer such environments independent of the location of the teachers and learners. There are two types of users in our platform, one is an admin user and the other type of user can be a lecturer and a learner depending on the course. Lecturer implies anyone who knows something well and can teach it and learner is anyone who is interested in learning. This departs from the classical educational course room context. 
Learner users can enroll in a learning experience where s/he will utilize resources and solve problems. They can monitor their progress of enrolled course.  They can create notes related to what they are learning  and share notes with others. They can also connect notes, annotate and tag them. 
Lecturer can create a course and decide to its content. Lecturers  can organize in-person meetings by specifying locations, dates, duration, and other relevant information using the platform. Lecturers can also  create polls to help the students to contribute some decisions taken during the lecture. Polls can be in three options: anonymous mode, multiple answers, and quiz mode. Lecturer can also have reputations based on the feedback gathered by the learners as they learn.
This platform provides users to create their own a profile that describes their interest and their knowledge. Users be able to follow other users and be able to see the activities/achievements of those they follow in this platform. This platform offers semantic searching, browsing, and recommendations to offer a rich learning environment. The system of this platform makes recommendations based on the learning experience.
This platform supports Android, and Web so that it is available on both mobile and the web. We also take into consideration ethical concerns while designing our platform. Therefore, we follow the rules of KVKK and GDPR and the standards of W3C as a software project.

- 1.2	 Project Status
At the beginning of course, we were not experienced about the design issues. At first, we all discussed about tasks and made joint decisions. Afterwards, we started dividing each task into sub-tasks and tried to give responsibility to every member of the team. Each friday we have regular meetings. We talk about the assignments at the hand, the status of our project, what we will do next week, and how to distribute the given tasks. We assign each task to someone and decide about a deadline for each task. Everyone comes forward for every task and does the tasks before the deadline.
First, we created a communication plan because we need to be in contact all the time. In order to do that, we created groups on Whatsapp and Slack in the first team meeting. Then, we focused on our project and decided about the requirements. We created mock-ups and scenarios. We met with the customer and rearranged requirements considering the customer’s wishes. Then, we focused on mainly on design and created use case diagram, class diagram, sequence diagram.

- 1.3  Forward Plans
We have created a guideline to help us implement the project until now.  We will decide about our project plan to know the time a task will be finished. We will start the implementation of the app. We need to decide which team members will develop frontend, backend and mobil application. We are going to discuss about the tools and frameworks, which might be useful for us. We need to find out which programming languages, services and APIs to use and conduct research and learning on those tools. We know that through the life time of project we will run across some obstacles. So, we will continue to arrange meetings frequently about those situations to ensure that everything is clear.

**Comment by hsuleerkul** [comment]
We can add it to the Milestone Report. Thank you!
