### ISSUE TITLE
Evaluation of Project Repository

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#143]
### Task:

As stated in issue #132 :  Evaluation of Communication Plan will be written. 
This evaluation will be written on our project repository: how we customized the repo, pros and cons, etc.

### Place To Put The Documentation:
Milestone 1 Report

### Deadline: 
15.04.2022 12.00

**Comment by hsuleerkul** [comment]
Hey @yilmaz-burak, I added a brief explanation on this part in #132, if it is unclear or you have questions you can ask me!

**Comment by yilmaz-burak** [comment]
# Welcome Page - README.md
This is where the people see when they first visit the repo. So, it is important. There, we have created an introductory page as to who the team members are, with their profile photos. We were a bit late to do that, but we have completed and created a good looking welcome page.

# Wiki Page
This is where all of our documentation resides. We have developed this page with the following headers as we kept on doing researches, adding documents etc. As a result, we have created a simple and minimalistic wiki page.

## Requirements
We simply listed all our requirements here. Similar to wiki page, this one is also relatively simple and minimalistic. For ease of readability, we also created dropdown-like buttons using HTML.

## Questions about Requirements
We have gathered the questions to be asked to customer. After the meeting, we have concluded the answers under the corresponding questions. This helped us keep the misconceptions/problems organized.

## User Scenarios and Mockups
Under this topic, 3 links have been created, each with their corresponding use cases and their mockups.
Overall, it led to easy access to the scenarios, also keeping them organized and uniform.

## Diagrams
We gathered all our diagrams under this header.
### Use Case
Under this, we have put our use-case diagrams.
### Class
Under this, we have put our class diagrams.
### Sequence
Under this, we have put our sequence diagrams individually.

## Team Members
We have all created a personal page under this. This makes the repo a bit more special, showing diversity of the team. A good touch indeed.

## Communication
We have created our communication plan and documented under here. It helped us uniform and showcase them with ease.

## Meeting Notes
For each week, note taker documented their notes here. Again, simplicity and availability is the first criteria.

## Research
In this repo, apparently, we all could have 'contributed' by editing some small details. However, we chose to gather necessary info in Slack channel, assigning a teammate to summarize under this topic. This cost us much.

## Templates
For any type of template, used this to keep track of and easily find the templates. This was helpful especially for creating some documentation conventions.

## Personal Effort
We have stored our weekly efforts under here weekly. Helped us solidly showcase our hardwork.

# Issue Tracking
For each atomic tasks, we usually created the issues and assigned themselves. For batch processes, we created an issue for tracking the batch effort, where everyone needed to bind their work together/needed to work together. This again helped us remove some chaos from the issues, keeping them necessarily intact.

# Customizations
* For more distinct and understandable issues, we have created multiple tags covering different necessary meanings.
* We have created an issue template so that the issues would look uniform, leading to less distraction on different issues. Although, having done that in the earlier stages would be better.

**Comment by hsuleerkul** [comment]
Thank you! It is ready to be added to the Milestone report.
