### ISSUE TITLE
Writing the Deliverables in a Table with Statuses

### ISSUE THREAD

**Issue by Brunettow** [bounswe/bounswe2022group3#144]
### Task:
All delivarables should be documented in a tabular form with their statuses, due dates and delivery dates.

Statuses:
* In Progress
* Delivered

Place To Put The Documentation:
Milestone 1 Report (After its done there will be a link here)

Deadline:
14.04.2022 21.00

Reviewer:
@ersoykadir

**Comment by Brunettow** [comment]
Tables can be reached [here](https://docs.google.com/document/d/1m_ewYXL1D9ZpDvGwDHW1sdv2X5Lu3jQPRvlRcAPSRI8/edit?usp=sharing). (One of them is an alternative)

### Table 1:
![image](https://user-images.githubusercontent.com/63921045/163493077-d4473721-c199-4ceb-88a5-ede92ca1dcaf.png)


### Table 2:
![image](https://user-images.githubusercontent.com/63921045/163493210-1d4fe2f8-71b7-4fd4-882b-231480977d2e.png)

**Comment by Brunettow** [comment]
## List and Status of Deliverables:

|Deliverable Name |Delivery Status |Due Date |Delivery Date|
| --- | --- | --- | --- |
| D1- Project Repository |Delivered | 08/03/2022|07/03/2022|
| D2- Requirements | Delivered | 30/03/2022|29/03/2022|
| D3- Software Design Documents in UML |Delivered|06/04/2022|04/04/2022|
| D4- Project Plan & RAM | Delivered | 15/04/2022|14/04/2022|
| D5- Milestone Report | Delivered | 15/04/2022|15/04/2022|

**Comment by salimtirit** [comment]
Great Job! Would it be better to put the links of the deliverables? I am not sure.

**Comment by hsuleerkul** [comment]
Table of Contents will do what you want. This table is ready to add to the report.
