### ISSUE TITLE
Composing the Report

### ISSUE THREAD

**Issue by bilalcim** [bounswe/bounswe2022group3#145]
### Task
As stated in #132, I will compose the report from
* the evaluations created by others (linked in issue #132),
* requirements,
* class diagrams,
* use case diagrams,
* sequence diagrams
using the [VSCode Markdown PDF](https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf) tool explained [under](https://github.com/bounswe/bounswe2022group3/issues/135#issuecomment-1099454157) issue #135.

### Required tools (if applicable) or researches:
VSCode Markdown PDF.

### Place to Put the Documentation
I will add the report under the deliverables section. Also, I will send it over to the communicator for submission to Moodle.

### Deadline
April 15, 22:00.

**Comment by hsuleerkul** [comment]
We uploaded the report. Thank you @bilalcim @ersoykadir
