### ISSUE TITLE
Preparing Project Plan for Milestone 1

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#148]
We have completed many assignments, spent hours on zoom meetings and closed dozens of issues. We want to show all of the previous work done as well as our estimations and plans for the the future. A project plan would be great for visualizing all of our work, timelines, and collaborations.

I have been researching and learning about ProjectLibre. The whole team came together in the last two days and managed to create a draft. You can find the pdf file with the  `.pod` file that you can use with [ProjectLibre](https://www.projectlibre.com/).

### Tools
- Project Libre
  Project Libre is a free planning program, especially focused on planning with a team over a long lifespan. It has a nice way of showing all the jobs, dependencies, and assignees. You can learn more about Project Libre  [here](https://www.projectlibre.com/).

**Comment by muhammetssen** [comment]
Draft 1:
[Group3-ProjectPlanv2.pdf](https://github.com/bounswe/bounswe2022group3/files/8496459/Group3-ProjectPlanv2.pdf)

**Comment by hsuleerkul** [comment]
I have reviewed the pdf file and cross checked it with RAM. There seems to be no problems. We can add it into our report. Eline sağlık!
