### ISSUE TITLE
Reviewing of the Weekly Efforts #7

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2022group3#150]
All the team members should report their weekly efforts in this [wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Week-7-Personal-Efforts) 

Note: Be careful that this is the previously unforgotten efforts. This is not for this week.  

So far:
- [x] Arif Akbaba
- [x] Bilal Aytekin
- [x] Mehmet Gökberk Arslan
- [x] Nurlan Dadashov
- [x] Hatice Şule Erkul
- [x] Kadir Ersoy
- [x] Ahmet Kudu
- [x] Muhammet Şen
- [x] Bengisu Takkin
- [x] Burak Yılmaz
- [x] Salim Kemal Tirit
- [x] Mertcan Özkan

Deadline: 24.04.2022, 23.59

**Comment by muhammetssen** [comment]
@yilmaz-burak Can you close this please 😿
