### ISSUE TITLE
Document user (lecturer) requirements

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#17]
Work on a draft for user requirements with @Brunettow and specify `Lecturer` requirements. Lecturer requirements will diverge from user requirements in couple of cases rather than them user requirements will be common between lecturer and learner. 

Reviewer: @mertcan-ozkan 
Deadline: 16.03.2022

**Comment by salimtirit** [comment]
https://docs.google.com/document/d/1ki2LBx20iFoFAwECgtnkoXY6DorYuKr6PLcuYvwjw8A/edit?usp=sharing
This is a draft for all user requirements [requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements) page will be updated after our questions.

**Comment by salimtirit** [comment]
Needs review from @mertcan-ozkan

**Comment by mertcan-ozkan** [comment]
User (lecturer) requiremets draft reviewed. Everthing looks good.
