### ISSUE TITLE
[Practice App]: Implementing a watchlist

### ISSUE THREAD

**Issue by bilalcim** [bounswe/bounswe2022group3#174]
# Task
As per the practice application task, we have investigated some cool API's to interact with in our endpoints. I have chosen the [TheMovieDB API](https://www.themoviedb.org/documentation/api) to implement a watchlist feature for the users of our practice application.
## Views
The watchlist feature will have the following views:
1. One main view where the user can either
i. enter part of a movie's name to get all matching results,
ii. or enter a full movie name to add it to their watchlist.
2. A result page for (i) above.
3. Also on the main page will be a button that shows the user his/her watchlist.

## Endpoints
The above views will make use of the following endpoints:
1. The `search` endpoint is a `POST` method which, given a `keyword`, gets the related results.
2. The `getWatchlist` endpoint is a `GET` method which returns the user's watchlist.
3. The `addMovie` endpoint is a `POST` method which, given the full title of the movie, adds the movie to the user's watchlist.

## Model
To store movies, I have created a `movies` relation which is represented by the following schema:
- `id`: The id of the movie as assigned by the API.
- `title`: The original title of the movie.
- `overview`: An overview of the movie as created by the API.
- `release_date`: The original release date of the movie.
- `vote_average`: Average vote for the movie.
- `username`: The username of the user.

The `id` and `username` together compose a primary key for this relation.

#### Deadline: 15.05.2022, 23:59.

**Comment by muhammetssen** [comment]
Done!
