### ISSUE TITLE
Document user (learner) requirements

### ISSUE THREAD

**Issue by Brunettow** [bounswe/bounswe2022group3#18]
Work on a draft for user requirements with @salimtirit while focusing on requirements for learner, which is a specific type of user shall be documented. These requirements will be documented on the [requirements page](https://github.com/bounswe/bounswe2022group3/wiki/Requirements).

Reviewer: @yilmaz-burak 
Deadline: 16.03.2022

**Comment by yilmaz-burak** [comment]
After resolving our questions with the customer, I'll be reviewing the requirements again. For now, looks good.

**Comment by yilmaz-burak** [comment]
Closing the issue, since requirements look adequate.
