### ISSUE TITLE
[Practice App]: Designing Class Diagrams 

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#188]
As a part of the design of our practice app, we will create class diagrams to visualize the structure of our application. Everyone will prepare the diagram for their own topic.
You can see the diagrams [in LucidChart](https://lucid.app/lucidchart/5852105b-a0c0-48db-bb19-1c3aa2b44bd1/edit?invitationId=inv_a38cd7a8-e1bb-446a-bed0-a9d7772c4266) and [in wiki](https://github.com/bounswe/bounswe2022group3/wiki/Practice-App-Class-Diagrams)
#### Icons 
| Person | Topic | Status| 
| --- | --- | --- |
|Arif Akbaba| | ✅   |
|Mehmet Gökberk Arslan|Cryptocurrency | ✅  |
|Bilal Aytekin| | ✅  |
|Nurlan Dadashov| Chess | :white_check_mark:  |
|Hatice Şule Erkul| Quiz | ✅ |
|Kadir Ersoy| Users | :white_check_mark:  |
|Ahmet Kudu| | ⬜  |
|Muhammet Şen| Tweet| :white_check_mark:  |
|Bengisu Takkin| Email Verifier | ✅  |
|Burak Yılmaz| | ✅   |
|Salim Kemal Tirit| | ✅   |
|Mertcan Özkan| | ✅  |

**Comment by ersoykadir** [comment]
Status checkboxes not working.

**Comment by nurlandadashov02** [comment]
Reviewed by the team.
