### ISSUE TITLE
[Practice App]: Designing Sequence Diagrams

### ISSUE THREAD

**Issue by Brunettow** [bounswe/bounswe2022group3#189]
As a part of the design of our practice app, we will create sequence diagrams to visualize the structure of our application. Everyone will prepare the diagram for their own topic.
You can see the diagrams in [here](https://github.com/bounswe/bounswe2022group3/wiki/Practice-App-Sequence-Diagrams).

| Person | Topic | Status| 
| --- | --- | --- |
|Arif Akbaba| | :white_check_mark: |
|Mehmet Gökberk Arslan| Cryptocurrency| ✅   |
|Bilal Aytekin| | ✅  |
|Nurlan Dadashov| | ✅  |
|Hatice Şule Erkul| | ✅  |
|Kadir Ersoy| Users | :white_check_mark:  |
|Ahmet Kudu| | ⬜  |
|Muhammet Şen| | :white_check_mark:  |
|Bengisu Takkin| Email Verifier | ✅  |
|Burak Yılmaz| currency converter | :white_check_mark:  |
|Salim Kemal Tirit| | ✅  |
|Mertcan Özkan| | ✅ |

Deadline: 20.05.2022, 23.59
Reviewer: @Brunettow

**Comment by nurlandadashov02** [comment]
Reviewed by the team
