### ISSUE TITLE
[Practice App]: Preparing Use Case Diagrams

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#195]
As a part of the design of our practice app, we will create use case diagrams to visualize the use cases of our application. Everyone will prepare the case diagram for their own topic.
You can see the diagrams [in LucidChart](https://lucid.app/lucidchart/6c462932-b0ce-41fb-b8d4-62b0905d67f3/edit?invitationId=inv_81b9dcf8-9473-4499-8a92-2046776d987b)
### People
- [x] Arif Akbaba
- [x] Mehmet Gökberk Arslan
- [x] Bilal Aytekin
- [x] Nurlan Dadashov
- [x] Hatice Şule Erkul
- [x] Kadir Ersoy
- [ ] Ahmet Kudu
- [x] Muhammet Şen
- [x] Bengisu Takkin
- [x] Burak Yılmaz
- [x] Salim Kemal Tirit
- [ ] Mertcan Özkan

Deadline: 20.05.2022

**Comment by muhammetssen** [comment]
Done!
![Practice-App Use Case Diagrams](https://user-images.githubusercontent.com/15876225/169591028-2179d3fa-b351-4a4d-abbf-e01462959127.png)
