### ISSUE TITLE
[Practice App]: Documenting User and System Requirements for Currency

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#197]
The User and System Requirements for the Currency Converting shall be identified and documented at [Practice App Requirement wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Practice-App-Requirements).

Deadline: 19.05.2022 23.59

**Comment by yilmaz-burak** [comment]
### User Requirements

* 1.3.1. The user shall be able to fetch currency exchange rates from USD.
   * 1.3.1.1. The user shall be able to get a list of [USD, EUR, TRY, AZN] currency conversions from USD from the UI of the project.
   * 1.3.1.2. The user shall be able to get a list of currency conversions from USD by providing a list of currencies for the endpoint relevant to the process of currency conversion via post request.
* 1.3.2 The user shall be able to convert a unit of currency to some other unit of currency.
   * 1.3.2.1 User shall be able to either use UI or the endpoint of the system by providing `from`, `to` currency strings and `amount` number to convert `number` amount of `from` currency to some unit of `to` currency depending on the exchange rate.

**Comment by nurlandadashov02** [comment]
Reviewed by the team.
