### ISSUE TITLE
[Practice App]: Sequence Diagram for Currency

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#198]
As a part of the design of our practice app, we are supposed to create sequence diagrams to visualize the flow of our application.  

This one is for the currency converting features of the practice application.

Deadline: 20.05.2022, @23.59

**Comment by yilmaz-burak** [comment]
Initial draft is ready!

![image](https://user-images.githubusercontent.com/46003469/169166055-cea411a3-3d65-4ded-854e-e351a92da5aa.png)

**Comment by muhammetssen** [comment]
LGTM!

**Comment by nurlandadashov02** [comment]
Reviewed by the team.
