### ISSUE TITLE
[Practice App]: Use Case/ Class/ Sequence Diagrams for Tweet Analytics

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#203]
I will prepare diagrams to represent usage flow of analytics tool for tweets.

A user can:
- Create a new rule system will listen to
- Get currently available rules
- Get average word counts and average lengths of tweets grouped according to hashtags

Deadline: 19.05.2022

**Comment by muhammetssen** [comment]
Use Case Diagram:
<img width="749" alt="image" src="https://user-images.githubusercontent.com/15876225/169406484-154ae692-24e5-46f8-a938-aba1dc573a12.png">

**Comment by muhammetssen** [comment]
Class Diagram:
<img width="477" alt="image" src="https://user-images.githubusercontent.com/15876225/169410113-66a88560-af25-4334-ac9e-525aa3ddc1dc.png">

**Comment by muhammetssen** [comment]
Sequence Diagram:
![image](https://user-images.githubusercontent.com/15876225/169412169-c8546d96-134f-457d-9d95-f900d47ea877.png)
[PlantUML Link](http://www.plantuml.com/plantuml/umla/ZP31IZin4CRlUOgX_ql_XnvKK5YbT6bx42g8hGymcmmXk9lMpCJYsxlP8EbMeUubcVtc--QNMR1WaDYrYj-SFs303fZU8tbDJyICbkhMMG-Ql52uLwXb7o1_hqm1a27sf-gzuhGxe1UOIBKx4iaagP9kOtbtT28KwkV7eQEKog1WWqmfVbNkgSiqIfoq14Cqr1xRppwIbL8906RpFAe2I_8IM-BfVrLhSHyeb2NuTtDxfw-lLAvwXsagsAutw-MkRpODp4hAnh4yR2KuR-VPCAXfrfcu8XoD-G64nYIWgQ2j8BikevMjL71YLEN_AIqBIkJbtb05pak9oRn5lanhIOOLS-BbyLl_jj7Qsa2MXCOhpSTtuiffcPzpvevV61VaJUpQBm00)

**Comment by hsuleerkul** [comment]
LGTM!
