### ISSUE TITLE
[Practice App]: Documenting User and System Requirements for Email Verifier

### ISSUE THREAD

**Issue by Brunettow** [bounswe/bounswe2022group3#206]
The User and System Requirements for the Email Verifier shall be identified and documented at [Practice App Requirement wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Practice-App-Requirements).

Deadline: 20.05.2022, 23.59

**Comment by Brunettow** [comment]
#### Requirements:
* The user shall be able to verify an email via providing an email address.
* The user shall be able to save an email via providing an email address.
* The user shall be able to view email addresses that is previously saved.

**Comment by nurlandadashov02** [comment]
Reviewed by the team.
