### ISSUE TITLE
Documenting User and System Requirements for Watchlist

### ISSUE THREAD

**Issue by bilalcim** [bounswe/bounswe2022group3#207]
# Task
The requirements of the watchlist feature will be identified and documented.

# Place to Put the Documentation

The [practice app requirements](https://github.com/bounswe/bounswe2022group3/wiki/Practice-App-Requirements) page.

#### Deadline: 20.05.2022, 23:59.

**Comment by bilalcim** [comment]
The requirements for the watchlist feature are documented at [#224](https://github.com/bounswe/bounswe2022group3/issues/224).

**Comment by nurlandadashov02** [comment]
Reviewed by the team.
