### ISSUE TITLE
[Practice App]: Use Case/Class/Sequence Diagrams for Posts

### ISSUE THREAD

**Issue by arfakbaba** [bounswe/bounswe2022group3#218]
As a part of the design of our practice app, we are supposed to create use case/ class/ sequence diagrams. I will create these diagrams for the post feature.

A user can:
- Create a new post,
- Get all posts of users
- Save created post in database

 Deadline: 20.05.2022, @23.59

**Comment by arfakbaba** [comment]
First Draft of Class Diagram
![image](https://user-images.githubusercontent.com/66492431/169480879-2389a85f-3e5c-481c-a613-9f491b46a9be.png)

**Comment by arfakbaba** [comment]
First draft of Use Case Diagram
![image](https://user-images.githubusercontent.com/66492431/169487010-129c33db-7810-4119-9f55-33fe1aed832c.png)

**Comment by nurlandadashov02** [comment]
Reviewed by the team.
