### ISSUE TITLE
Document System-Annotation Requirements

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#22]
Sub-topic `annotation` of System Requirements shall be identified from the project description. A draft for these requirements will be documented on the [Requirements page](https://github.com/bounswe/bounswe2022group3/wiki/Requirements).

Reviewer: @arfakbaba 
Deadline: 16.03.22

**Comment by yilmaz-burak** [comment]
Some notes:

Support annotating with text
Support annotating with image

If the text is a URI, served as a hyperlink and creates an external link to other resources. (as a hyperlink):
- Should it be in-interface or directly open preferred external resource?

support Links —> Semantic resources:


More like non-functional (?):
comply with the W3C Web Annotation Data Model [1] and follow W3C
standards [2]

**Comment by yilmaz-burak** [comment]
After getting answers from the customer, will be revised. So far, draft is in [Requirements page](https://github.com/bounswe/bounswe2022group3/wiki/Requirements), subtopic `2.6 Annotation`

**Comment by arfakbaba** [comment]
Closing this issue since, requirements are reviwed and seem adequate.
