### ISSUE TITLE
[Practice App]:Documenting User and System Requirements for Post-feature

### ISSUE THREAD

**Issue by arfakbaba** [bounswe/bounswe2022group3#229]
The User and System Requirements for the Posts feature shall be identified and documented at [Practice App Requirement wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Practice-App-Requirements).

Deadline: 20.05.2022, 23.59

**Comment by arfakbaba** [comment]
![image](https://user-images.githubusercontent.com/66492431/169473175-9b75e474-97e4-4431-9086-5f6a4e9f45c9.png)

**Comment by arfakbaba** [comment]
System requirements :
![image](https://user-images.githubusercontent.com/66492431/169473525-0f1dd8b1-0651-4e6d-83d0-e7b01a138fab.png)

**Comment by muhammetssen** [comment]
Done!
