### ISSUE TITLE
Document Note taking requirements

### ISSUE THREAD

**Issue by arfakbaba** [bounswe/bounswe2022group3#23]
Note taking requirements shall be identified from the project description. A draft for these requirements will be documented on the [Requirements page](https://github.com/bounswe/bounswe2022group3/wiki/Requirements).

Reviewer: @Goko6 
Deadline: 16.03.22

**Comment by yilmaz-burak** [comment]
Where should the note taking take place? On profile or after lectures or etc?

**Comment by Goko6** [comment]
Note taking requirements are reviewed. Closing the issue after some rephrasing.
