### ISSUE TITLE
[Practice App]: Swagger API Documentation for Post Feature

### ISSUE THREAD

**Issue by arfakbaba** [bounswe/bounswe2022group3#231]
## Task
Documentation for quiz api will be on Swagger as team decided. I will provide docmentations for endpoints : 

- GET `/posts/getPost`
- POST`/posts/createPost` and  - POST `/posts/savePost`

**Comment by arfakbaba** [comment]
![image](https://user-images.githubusercontent.com/66492431/169490126-6965e35d-b3fc-470f-8ae5-795475196cfb.png)

**Comment by arfakbaba** [comment]
![image](https://user-images.githubusercontent.com/66492431/169490766-712de501-b525-4fcd-963d-861f04959cc9.png)

**Comment by muhammetssen** [comment]
Done!
