### ISSUE TITLE
[Practice App]: Writing Executive Summary

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#234]
I will prepare a summary to describe the current status of our application and challenges we encountered.

You can find the summary in our [wiki page](https://github.com/bounswe/bounswe2022group3/wiki/Practice-App-Executive-Summary) 
These are the required items from project submission instructions:
- Summary of project and overall status
- URL of your deployed application (including any information we may need to test your
application)
- API URL (documented) – this part was described in detail in your assignment description.
- Basic functionality of your project
- Challenges you met as a group
-  List the status of deliverables.

Deadline: 20.05.2022

**Comment by nurlandadashov02** [comment]
Reviewed by the team.
