### ISSUE TITLE
[Practice App] Use Case / Class / Sequence Diagrams for Quiz Feature

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#235]
## Task

There is a need of UML diagrams to explain quiz feature's functionality. I will add explanations for them asap.

## Tools 
[Draw.io](https://app.diagrams.net/)
[PlantUML](https://plantuml.com/)

**Deadline:** 20.05.2022 18.00

**Comment by nurlandadashov02** [comment]
Reviewed by the team.
