### ISSUE TITLE
[Practice App]: Writing an Evaluation of Tools Used

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#236]
Task:
I need to write the evaluation of the tools we have used to manage our practive app project.
I will evaluate the following platforms:

- [x] Github
- [x] Swagger
- [x] Postman
- [x] MongoDB
- [x] Lucid app
- [x] PlantUML
- [x] ProjectLibre
- [x] Slack
- [x] Whatsapp
- [x] Zoom

Deadline:
20,05,2022 20.00

**Comment by salimtirit** [comment]
[Github](https://github.com/)
Github is the main platform we used in our project. Basically, we did everything and put everything on Github. In the meetings, after discussing the meeting agenda and deciding who will do what we wanted everyone to open a related issue for that task. We have used the issue system to track our progress. It increased our collaboration since we could comment on issues. We have used the branches to work together. Everyone created a seperate branch for their part. The branches were very effective. We used pull requests to check conflicts or errors before merging. We checked each others work.

**Comment by salimtirit** [comment]
[Swagger](https://swagger.io/docs/)
Swagger is the tool we have used in our API documentation creation. It is easy to use and write. It made our documentation process easier. The only problem may be writing everything without any help. One may get lost here.  Overall it is a good tool and helped us very much.

**Comment by salimtirit** [comment]
[Postman](https://www.postman.com/)
Postman is the tool we used to test API requests and responses. It has a nice user interface and there are many resources to learn how to use it. It helped us in every stage of our implementation since we first tested the external APIs and our own APIs.

**Comment by salimtirit** [comment]
[MongoDB](https://www.mongodb.com/) 
We used mongoDB as our database. It makes database usage easier and more effective. It has nice documentation and very large community. It is an important tool to learn.

**Comment by salimtirit** [comment]
[Lucid.app](https://lucid.app/)
We used the lucid app to draw our diagrams. It allows us to work together on the same document. For example in the class diagrams everybody created their own class that they implemented. For the use case diagram, we build it part by part in the same graph and reviewed it in a meeting. It provides a solid, collaborative environment with many beautiful options of shapes. It is easy to use, moving objects and connecting them with arrows is pretty easy.

**Comment by salimtirit** [comment]
[PlantUML](https://plantuml.com/)
We used plantUML to create sequence diagrams. It takes care of the drawing part itself and it is closer to coding. It creates arrows, “alt” or “for” boxes in a structured fashion. It creates the actors, participants, and database automatically. It is also symmetric about these one on the top and one on the bottom. It can also be used to create other types of diagrams but it is easier to do them with lucid app

**Comment by salimtirit** [comment]
[ProjectLibre](https://www.projectlibre.com/)
We used project libre to prepare our project plan. It is open-source, free software. It is a desktop application and it is stated that there will be a cloud version. Apparently, the cloud version is being waited for a long time. Since it is only available as a desktop application we could not efficiently work on it. It was not practical to share the screen on zoom and try to fill a table together. It is not stable on different operating systems. We didn’t like this program at all. It didn’t make our job easier than it is. We are very disappointed about this.

**Comment by salimtirit** [comment]
[Slack](https://slack.com/)
We used slack as a platform to communicate with our friends and teachers about the project. We asked questions and checked the answers. We created a separate workspace for our group only. We used it to communicate between the group members, share helpful links, and bring together questions. Creating different text channels helped us increase our productivity since we could easily follow multiple topics at a time.

**Comment by salimtirit** [comment]
[WhatsApp](https://www.whatsapp.com/)
We used WhatsApp to communicate instantly and discuss small things. Since we all are used to checking WhatsApp frequently it helped us communicate. WhatsApp is generally hard to track so we didn’t use it for very important subjects that need to be checked by all team members. Generally, when we needed help or were not sure about a subject we used WhatsApp. We also used it for general chit-chat from time to time.

**Comment by salimtirit** [comment]
[Zoom](https://zoom.us/)
We used zoom for meetings. The problem with the zoom is that since there is a time limit to the free version of the zoom our meetings got interrupted. We shared our screens when we needed them and used the chat feature to share some links.

**Comment by nurlandadashov02** [comment]
Reviewed by the team.
