### ISSUE TITLE
[Practice App]: Documenting User and System Requirements of Quiz 

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#242]
## Task

The documentation of user and system requirements for the quiz feature should be documented. I will take our main [Requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements) for referance. 

## Documentation Place

[Practice-App Requirements](https://github.com/bounswe/bounswe2022group3/wiki/Practice-App-Requirements)

**Deadline:** 20.05.2022 20.00

**Comment by hsuleerkul** [comment]
I have finished this task. Waiting for review!

## User Requirements

### 1.10. Quiz
* 1.10.1. The user shall be able to create a quiz, choosing following properties of a quiz: number of questions, categories of questions, difficulty of questions.
* 1.10.2. The user shall be able to view all of the quizzes that he/she created.
* 1.10.3. The user shall be able to view questions of a quiz that he/she created.
* 1.10.4. The user shall be able to view all of the quizzes that he/she created.
* 1.10.5. The user shall be able to view available question categories.


## System Requirements

### 2.9. Quiz

* 2.9.1. System shall save all quizzes created by a user into database. 
* 2.9.2. System shall ensure that a quiz is only visible to the user created it. 
* 2.9.3. System shall provide an interface to view the users' saved quizzes.
* 2.9.4. System shall provide an interface to view a quiz given its id.
* 2.9.5. System shall provide an interface to choose multiple category, question amount and difficulty for a quiz.
* 2.9.6. System shall provide an endpoint to create a quiz.
* 2.9.7. System shall provide an endpoint to get a quiz.
* 2.9.8. System shall provide an endpoint to get all quizzes of a user.
* 2.9.9. System shall provide an endpoint to get available categories.

**Comment by yilmaz-burak** [comment]
LGTM!
