### ISSUE TITLE
[Practice App]: Use Case Diagrams for Currency

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#245]
As a part of the design of our practice app, we are supposed to create use case diagrams to visualize the functionality of our project.

This one is for the currency converting features of the practice application.

Deadline: 20.05.2022, @23.59

**Comment by yilmaz-burak** [comment]
![image](https://user-images.githubusercontent.com/46003469/169581170-6f8167da-9eb8-420b-aed5-6652106c810f.png)

Done!

**Comment by nurlandadashov02** [comment]
Reviewed by the team.
