### ISSUE TITLE
[Practice App]: Class Diagram for Currency

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#246]
As a part of the design of our practice app, we are supposed to create class diagrams to visualize the inner workings of our project.

This one is for the currency converting features of the practice application.

Deadline: 20.05.2022, @23.59

**Comment by yilmaz-burak** [comment]
![image](https://user-images.githubusercontent.com/46003469/169582125-a4be4c1e-e76a-433c-bfac-57c43a8c0de5.png)
Done!

**Comment by nurlandadashov02** [comment]
Reviewed by the team.
