### ISSUE TITLE
[Practice App]: Drawing movies diagrams

### ISSUE THREAD

**Issue by bilalcim** [bounswe/bounswe2022group3#247]
# Task
As per the practice application assignment, I will draw the

- [x] use case,
- [x] sequence,
- [x] and class

diagrams for the movies endpoint.

# Place to put the documentation
The relevant LucidChart's and, finally, the practice app group submission.

# Tools
- LucidChart.
- draw.io.

#### Deadline: 20.05.2022, 23:59.

**Comment by bilalcim** [comment]
The diagrams are ready:

# Use Case Diagram - Movie
<img width="484" alt="Screen Shot 2022-05-20 at 20 54 56" src="https://user-images.githubusercontent.com/44259352/169584978-b69baa8b-b827-4ae8-ba48-26508b2492b2.png">

# Class Diagram - Movie
<img width="665" alt="Screen Shot 2022-05-20 at 20 55 15" src="https://user-images.githubusercontent.com/44259352/169585017-8e68fa47-3ab0-4254-b3ea-c058299d7a84.png">

# Sequence Diagram - Movie
![uml](https://user-images.githubusercontent.com/44259352/169585776-4dd4099d-5b4c-4977-9693-e81892564178.png)

**Comment by nurlandadashov02** [comment]
Reviewed by the team.
