### ISSUE TITLE
Requirements for Event Organization

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#25]
A draft of requirements for event organization system should be identified and documented on the [requirements](https://github.com/bounswe/bounswe2020group6/wiki/requirements) page.

Reviewer: @ahmetkudu 
Deadline: 16.03.2022

**Comment by ersoykadir** [comment]
* Lecturers shall be able to **organize** and **schedule** meetings.
  * Must specify;
    * Type: {Online, In-person}
    * Location: {Geolocation(in-person), Platform(online) }
    * Date
    * Duration
    * Context
    * Visibility: {only to enrolled users or public} ?
    * Fee ?
    * Attendance capacity: (What happens if very few people interested in event ? Maybe there should be a lower limit of attendance to organize the meeting and should be postponed or canceled otherwise?)
* Users shall be able to **join** the **attendance list** of the event that they would like to participate. 
  * Easy attendance with only one click.
  * System shall hold a list of attending users’ info. (Maybe visible to the lecturer?)
  * Users should be informed of the events via email ?
    * Link of the event meeting, if online
    * A document that specifies the event info (location and time) and entrance access to the event (conference room?), if in-person.

* Users should be **notified** of upcoming events of the lecturers whose classes that they enrolled in.
  * Maybe an upcoming events page or recommendation?
    * Shown to user by popularity of events(high attendance, almost full of attendance capacity)
    * Events of the lecturers of already enrolled classes needs higher priority?

**Comment by ahmetkudu** [comment]
Well done!
