### ISSUE TITLE
[Practice App]: Individual Report Preperation - Burak Yılmaz

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#255]
Each member needs to prepare an Individual Report showcasing the work they done with 
- Executive Summary
  - API 
    - Describe the API developed by your team
    - Describe the API you choose, explain functionality
  - Describe the tasks you have performed, any related issue and wiki cont.
  - Your Code, that introduces API functionality
    - Users controller, route and validate 
    - users model
    - users tests
    - auth.js and jwkeys.js
  - API documentation,
  - Sample call,
  - Explain any challenges 
- Code Review
  - Whose code you reviewed 
    - Name of team member
    - Provide relevant pull request, code review and conversation
    - Describe the review interaction and resulting code.
- Pull requests you created, describe
- Issues

Deadline: 20.05.2022 @ 23.59

**Comment by yilmaz-burak** [comment]
- [Executive Summary](#executive-summary)
  - [API](#api)
    - [Personal effort](#personal-effort)
      - [Burak Yılmaz](#burak-yilmaz)
    - [Code](#code)
      - [**currency.route**](#usersroute)
      - [**currency.validate**](#usersvalidate)
      - [**currency.controller**](#userscontroller)

    - [API documentation](#api-documentation)
      - [SampleCall](#samplecall)
      - [Sequence Diagrams](#sequence-diagrams)
      - [Use cases](#use-cases)
      - [Classes](#classes)
      - [Related Requirements](#related-requirements)
        - [User Requirements](#user-requirements)
        - [System Requirements](#system-requirements)
      - [Challenges](#challenges)
  - [Code Review and Pull requests](#code-review-and-pull-requests)
  - [Issues](#issues)
  - [Api docs](#api-docs)
# Executive Summary
## API
As a group, we have each created our own little projects by creating distinct endpoints, providing a unique functionality.
I have used a currency converting api, namely [currencyconverterapi](https://free.currencyconverterapi.com/) and by using its features, created a table for conversion rates. User can send a post request to `/currency/allConversions` endpoint to get rates between `USD` and `[USD, EUR, TRY, AZN]` currencies. Similar to this, users can also get the value of a currency in the form of another currency by sending a get request to `/currency/getConversion`.

### Personal effort
#### Burak Yılmaz
## Burak Yilmaz
- Created a release for the practice-app [here #248.](https://github.com/bounswe/bounswe2022group3/issues/248)
- Created class diagrams for currency [here #246.](https://github.com/bounswe/bounswe2022group3/issues/246)
- Created use case diagrams for currency [here #245.](https://github.com/bounswe/bounswe2022group3/issues/245)
- Created sequence diagrams for currency [here #198.](https://github.com/bounswe/bounswe2022group3/issues/198)
- Documented user and system requirements for currency [here #197.](https://github.com/bounswe/bounswe2022group3/issues/197)
- Documented API by Swagger for currency [here #194.](https://github.com/bounswe/bounswe2022group3/issues/194)
- Created unit tests for currency [here #192.](https://github.com/bounswe/bounswe2022group3/issues/192)
- Created backend for currency [here #191.](https://github.com/bounswe/bounswe2022group3/issues/191)
- Created frontend for currency [here #190.](https://github.com/bounswe/bounswe2022group3/issues/190)
- Reviewed the pr [Swagger Integration for Express #180.](https://github.com/bounswe/bounswe2022group3/issues/180)
- Reviewed the pr [Containerization #221.](https://github.com/bounswe/bounswe2022group3/issues/221)
- Reviewed the pr [Practice App/Lyrics #253.](https://github.com/bounswe/bounswe2022group3/issues/253)
- Attended all team meetings

### Code
Code can be found within the report folder. I have implemented  the currency route (/server/src/routes/currency)
#### **[currency.route](https://github.com/bounswe/bounswe2022group3/blob/master/practice-app/server/src/routes/currency/currency.route.js)** 
Declares the routes for the /currency. It has `getConversion` and `allConversions` configured.
![image](https://user-images.githubusercontent.com/46003469/169603035-b8834f61-9710-4c64-aa7d-09437b3af966.png)


#### **[currency.validate](https://github.com/bounswe/bounswe2022group3/blob/master/practice-app/server/src/routes/currency/currency.route.js)**
Provides the validity checks for requests coming, body of the post request, query parameters etc.
![image](https://user-images.githubusercontent.com/46003469/169603073-9815d2da-56ea-4cc0-a996-bb4baf341344.png)


#### **[currency.controller](https://github.com/bounswe/bounswe2022group3/blob/master/practice-app/server/src/routes/currency/currency.controller.js)**
Handles the API requests for the declared routes.
- `/currency/allConversions`:
   - This endpoint takes a post request with a body of `allCurrencies`, which is an array of currencies. The function loops over all the items in that array and makes a request to the external api. After the iteration is completed successfully, all the conversion rates are sent to the request origin. If any error is thrown (catch block), sends a 400 to the request origin.
-  `/currency/getConversion`:
   - This endpoint accepts get request with query parameters `from`, `to` and `amount`, representing both currencies and a float representing the amount of currency. The function parses the query to get the data and then gets the conversion rate through the external api. After the conversion rate is successfully fetched, multiplies the rate value by the amount, resulting in the amount of currency equivalent to the value of the initial currency. If any error is thrown (catch block), sends a 400 to the request origin.
![image](https://user-images.githubusercontent.com/46003469/169601440-827fc8fe-85d3-4c2e-a710-7ef1f7b9a531.png)
   - Used on main page, can be seen on a screenshot here(#190 ) 



#### **[/currency/index.js](https://github.com/bounswe/bounswe2022group3/blob/master/practice-app/client/pages/currency/index.js)**
![image](https://user-images.githubusercontent.com/46003469/169603207-034e95b3-6b1d-42ea-afe1-70274ea75d06.png)
![image](https://user-images.githubusercontent.com/46003469/169603433-0a662171-2430-4852-bba8-4655bdab5f6f.png)
![image](https://user-images.githubusercontent.com/46003469/169603487-3e5d37e2-8267-4ffe-b789-6492007564ea.png)


### API documentation
![swaggerss](https://user-images.githubusercontent.com/49765256/169414189-0258325c-c961-4d68-ae2a-a595661a1874.png)

#### SampleCall
![samplecall](https://user-images.githubusercontent.com/49765256/169549868-dc0ee10c-fbff-40b2-b42b-e75d40a1dc08.png)

#### Sequence Diagrams
![seq_register-pr](https://user-images.githubusercontent.com/49765256/169412744-7575ca61-3146-4966-9b24-4505243af33e.png)
![seq-log-pr](https://user-images.githubusercontent.com/49765256/169414329-7a264a9d-ebd8-4a24-a11b-6e2a6ee7d79e.png)

#### Use cases
![image](https://user-images.githubusercontent.com/49765256/169411220-198e2501-7911-48de-b46c-3f90889e5a0a.png)

#### Classes
![image](https://user-images.githubusercontent.com/49765256/169414242-11fbc227-4f11-4c77-99f3-2897bde22105.png)

#### Related Requirements
##### User Requirements
* 1.1.1. Login
   * 1.1.1.1. Users shall login to the system to use any feauture.
   * 1.1.1.2. Users shall be able to log into their account using their email and password combination.
* 1.1.2. Registration
   * 1.2.2.1 Users shall be able to register using a valid and unique email address, name, surname, and a password.
##### System Requirements
* 2.1.1. The System shall provide an access token that allows users to be authorized to see other pages when login requested.
* 2.1.2. The system shall save user data given in register requests to database.
  * 2.1.2.1. The system shall encrypt passwords with SHA-256 algorithm before saving to db.

#### Challenges
The most challenging part for me was to understand what a middleware does and how should i implement authorization middleware so that everyone can use it smoothly. 

## Code Review and Pull requests
I reviewed Muhammet Sen's code, @muhammetssen. In this [pull request](https://github.com/bounswe/bounswe2022group3/pull/199). There were no major problems except a variable naming conflict. He quickly resolved the problem and I approved the pr.
I received two code reviews for my two pull requests [#1](https://github.com/bounswe/bounswe2022group3/pull/166), [#2](https://github.com/bounswe/bounswe2022group3/pull/196). First pr was after I finished backend. Second one was after unit testing and frontend. Nurlan Dadashov, @nurlandadashov02 reviewed my code. He is more experienced in web dev than me and he helped a lot. He pointed out some error cases that I forgot to handle and also helped with frontend problems. I made the necessary changes and got approved.

## Issues
- [#248.](https://github.com/bounswe/bounswe2022group3/issues/248)
- [#246.](https://github.com/bounswe/bounswe2022group3/issues/246)
- [#245.](https://github.com/bounswe/bounswe2022group3/issues/245)
- [#198.](https://github.com/bounswe/bounswe2022group3/issues/198)
- [#197.](https://github.com/bounswe/bounswe2022group3/issues/197)
- [#194.](https://github.com/bounswe/bounswe2022group3/issues/194)
- [#192.](https://github.com/bounswe/bounswe2022group3/issues/192)
- [#191.](https://github.com/bounswe/bounswe2022group3/issues/191)
- [#190.](https://github.com/bounswe/bounswe2022group3/issues/190)
- [#180.](https://github.com/bounswe/bounswe2022group3/issues/180)
- [#221.](https://github.com/bounswe/bounswe2022group3/issues/221)
- [#253.](https://github.com/bounswe/bounswe2022group3/issues/253)
## Api docs
Api documentation can be found [here](http://ec2-3-70-92-135.eu-central-1.compute.amazonaws.com/api-docs/). My functionality listed under `User` section.

**Comment by muhammetssen** [comment]
LGTM!
