### ISSUE TITLE
Gathering questions about requirements

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#26]
The questions, ambiguous points about requirements will be gathered under this issue. They will be resolved at the discussion session with TA.

Deadline: 16.03.2022 20:00

**Comment by ersoykadir** [comment]
### Event Organization
- Should every user be allowed to organize events?
- Should events have entrance fee ?
- Should events be visible to every user or just the ones that are enrolled to the class? (for lecturer meetings)
- What happens if very few people interested in event ? Maybe there should be a lower limit of attendance to organize the meeting and should be postponed or canceled otherwise? (System should notify the users if the event got postponed or canceled) 
- Should we make an upcoming events feature in recommendations ?
  * Shown to user by popularity of events(high attendance, almost full of attendance capacity)
  * Events of the lecturers of already enrolled classes needs higher priority?

**Comment by yilmaz-burak** [comment]
### System - Annotation:
* What is the scope of annotation? (Where, when can it be used?)
* What extra types of content can be annotated? (Profile pages,)
* What are the restrictions on annotations?
* What are links for semantic resources?
*  Are there annotation restrictions? (Only lecturers can annotate outsourced files, etc?)

### System - Communicaton Channel:
* What is the difference between asking questions and discussion of ideas?
* What platforms can be taken reference for this? (github for mentioning etc, reddit, moodle, ... ?)

**Comment by ersoykadir** [comment]
### User
- Should the user verification made by phone or mail or else_
  - Should system send a message to the phone number for verification?
  - Should there be an Captcha?
- Will there be Guest User feature?
- Should user login to see course content?
- Will there be a course fee? Will there be a premium account?
- Should there be an option for registiration and login via social media accounts?
- Will the lecturers be allowed to give certificates?
####  Lecturer
- Should lecturers confirm their skills by showing a certificate?
#### Learner
- Should we consider learner education-experience for recommendations?
-

**Comment by ersoykadir** [comment]
### Communication Channel
- What type of platforms shoukld we take reference as? Moodle, Udemy etc.

**Comment by ersoykadir** [comment]
### Annotation
- If the text is a URI, served as a hyperlink and creates an external link to other resources. (as a hyperlink):
  - Should it be in-interface or directly open preferred external resource?
- What is the scope of annotating?

**Comment by ersoykadir** [comment]
### Note Taking
- Where should the note taking take place? On profile or after lectures or etc?
- Should the system provide learner to give permissions read-only,editing,delete to shared notes ?
- Note taking system as a github profile page and notes as repos ?

**Comment by ersoykadir** [comment]
### Uncategorized Questions
- How should the notification system work?
- Should the user be able to upload files to our server?
- Filtering system?

**Comment by ersoykadir** [comment]
Questions were discussed with TA and documented [here](https://github.com/bounswe/bounswe2022group3/wiki/Questions-to-Customer).
