### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#260]
## Issue
Our team requires a consistent way of creating issues. 
## Tasks
- [x]  Create issue template (.yaml) file
- [x]  Commit template under `.github/ISSUE_TEMPLATE`
## Deliverables
* template code
## Acceptance Criteria
* Team members are able to create issue in UI using new template
## Deadline of the issue
11.10.2022 @23.59

**Comment by nurlandadashov02** [comment]
Issue template has been created and [committed](https://github.com/bounswe/bounswe2022group3/commit/d88128ffeb3b86997e62dd7a28dcaa950ffe8ed5).
