### ISSUE TITLE
Communication Plan Update

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#262]
We should update our communication plan, since our schedules are different than the last semester. Also, we have decided on using Discord, rather than Slack, because of their free tier changes.

Deadline: 11.10.2022, 3PM

**Comment by yilmaz-burak** [comment]
We have created a poll on doodle.com, most people voted on Sunday 8-11 pm.

**Comment by muhammetssen** [comment]
Thanks!
