### ISSUE TITLE
Creating personal wiki pages

### ISSUE THREAD

**Issue by berkeozdemir2016400246** [bounswe/bounswe2022group3#264]
Every group member should prepare a personal page, introducing themselves. Check the older group members' pages for the template.

**Comment by furkanakkurt1335** [comment]
Thank you for the issue. I'd already created [a _short_ page](https://github.com/bounswe/bounswe2022group3/wiki/Furkan-Akkurt) for myself but it needs to be detailed. I'll try to add more information~.
