### ISSUE TITLE
Platform Name Suggestions

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#267]
### Issue

We need a name for our platform, which will be displayed on Wiki Home page. 

### Task(s)

- [x] Gather name suggestions
- [ ] Decide on a platform name.

### Deliverable(s)

* Platform name

### Acceptance Criteria

* Suggested names should be discussed between the team members and the one that is most liked should be chosen.

### Deadline of the issue

18.10.2022

**Comment by ersoykadir** [comment]
Possible options
- Bucademy
- Course Bucket
- Discite

**Comment by salimtirit** [comment]
Other Recommendations
- educat 
- course basket
- coursology
- bursera
- doctrina
- learn2gether
- coursemy
- bliss

**Comment by muhammetssen** [comment]
The ballot boxes are closed and our platform's name is Bucademy 🥳 🥳 
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/15876225/196645333-c8603d01-37bb-4b5f-b81b-1d32fa9ea6b0.png">
