### ISSUE TITLE
Updating Requirements

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#269]
### Issue

We have gone over and reviewed each element of the requirements with the team. The joint decisions of the group about each problematic part of the requirements are documented in [#16](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2316-11.10.2022) and [#17](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2317-12.10.2022) meeting notes. We need to split the work of updating them and do update all. Please, do not just copy paste but read and make sure the update is correct and resembles the view of the team.

### Task(s)

| Topic | Status | Person | 
| --- | --- | --- |
|Glossary| <ul><li>- [ ] </li></ul> |  @yilmaz-burak |
|1.1 Account Features| <ul><li>- [x] </li></ul> | @salimtirit   |
|1.2/1.4 Profile(UserReq) and Admin| <ul><li>- [x] </li></ul> | @berkeozdemir2016400246  |
|1.3 User Actions| <ul><li>- [x] </li></ul> | @ersoykadir  |
|2.1 Profile Page| <ul><li>- [x] </li></ul> | @mertcan-ozkan  |
|2.2 Communication Channel| <ul><li>- [x] </li></ul> | @arfakbaba   |
|2.3 Note Taking| <ul><li>- [x] </li></ul> | @ersoykadir  |
|2.4 Recommendations| <ul><li>- [x] </li></ul> | @Goko6  |
|2.5 Search Engine| <ul><li>- [x] </li></ul> | @bilalcim   |
|2.6 Annotation| <ul><li>- [x] </li></ul> | @furkanakkurt1335  |
|2.7 Notification*| <ul><li>- [x] </li></ul> | @hsuleerkul |
|3 Non-func reqs| <ul><li>- [x] </li></ul> | @nurlandadashov02 |

* Notification section doesn't exist in the current requirements and should be created on system requirements.

### Deliverable(s)

* Updated [requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements) section.

### Acceptance Criteria

* All updates stated in meetings [#16](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2316-11.10.2022) and [#17](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2317-12.10.2022) is done.

### Deadline of the issue

17.10.2022 @23.59

### Reviewer

Kadir Ersoy

### Deadline for Review

18.10.2022 @15.00

**Comment by ersoykadir** [comment]
Wanted to drop a requirement that was talked in meetings but missed in meeting notes. 
* The system shall notify users when the lecturer of their course organizes an event. Also they should be notified when the event time is approaching and event is cancelled. Notification requirement

**Comment by berkeozdemir2016400246** [comment]
Here are the changes I propose for 1.4. Admin User requirements:

Old:

>1.4. Admin User
>- 1.4.1. Admins shall be able to ban users for inappropriate behaviors.
>- 1.4.2. Admins shall be able to delete inappropriate comments and articles.

1.4. Admin User

- 1.4.1. Admins shall have access to all account features described in 1.1 except 1.1.1 and 1.1.2.2.
- 1.4.2. Admins shall be able to see all user profiles regardless of users' privacy status.
- 1.4.3. Admins shall be able to view all course contents regardless of courses' privacy status.
- 1.4.4. Admins shall be able to ban users for inappropriate behaviors.
- 1.4.5. Admins shall be able to delete inappropriate comments, notes, annotations and course material.
- 1.4.6 Admins shall be able to utilize the search engine to find specific posts and users.
- 1.4.7 The system should notify admins when a new report is made.
- 1.4.8 The system should provide an interface for admins to view and resolve reports.

For the glossary:

Reporting: The action taken by users to when they see another user behaving inappropriately. The admin users can then view those reports and choose to whether act on them or not and mark the issue as resolved.

Other related requirements:

1.3.15. Users shall be able to report comments, notes, annotations and course material to the admins if they think they are inappropriate.

**Comment by mertcan-ozkan** [comment]
These are the changes made:

| REQUIREMENT | OLD | NEW | CHANGES |
| --- | --- | --- | --- |
| | | | |
| | | | |
| | | | |

**Comment by hsuleerkul** [comment]
After adding notifications to thte system requirements these are the requirements I've written :

### 2.7. Notifications
* 2.7.1. The system shall provide in-app and push notifications.
* 2.6.2. The system shall send notifications to the users if any of the following happens: a course they have created has a new user enrolled, an event is created and/or cancelled in a course they are enrolled in, another users follows or requests to follow them, and a user they have sent following request accepts their request.

**Comment by salimtirit** [comment]
After our meeting on 16.10.2022, I wanted to mention the guest users' and other users' views when they enter the app need to be defined or somehow mentioned. Details can be found in the meeting notes.

**Comment by furkanakkurt1335** [comment]
I had updated the section _2.6 Annotation_, as well as adding 2 new requirements under the section (_1.3. User Actions_) regarding _annotation_ again, on 15 Oct as:

| Requirement ID | Body | Change Type |
| --- | --- | --- |
| 2.6.3 | The system shall provide a mechanism such that annotation can be applied to any ~~context~~ note or course content. | edit |
| 2.6.4. | The system shall highlight annotated text portions to emphasize annotation. | addition |
| 1.3.6.1. | User shall select a portion of the text to annotate. | addition |
| 1.3.6.2. | User should be able to turn on and off annotation visibility. | addition |

**Comment by Goko6** [comment]
Since the requirements we have written for recommendations were ambigious due to lack of information, I have updated it.

Old:

>2.4 Recommendations
>* 2.4.1. The system shall provide a list of recommended courses to learners.
>	* 2.4.1.1 The system shall provide learners the option to mark courses in the recommendations list as "not interested".
>* 2.4.2. The system shall rank courses that are similar to recently completed courses of the learner, courses that have the learner's previously completed courses as prerequisites and courses that are related to the learner's area of interests higher in the recommendations list.
>* 2.4.3. The system shall rank the courses of the lecturers with high reputation and courses of the learner's previous teachers higher in the recommendations list.

New:
2.4. Recommendations

* 2.4.1. The system shall provide a list of recommended courses to learners.
	* 2.4.1.1 The courses in the list shall either have semantically similar names to the courses that the learner has completed previously or have tags that match with the learner's interests.

**Comment by bilalcim** [comment]
Here are the _revised_ requirements for **2.5. Search Engine**.

| REQUIREMENT | OLD | NEW | CHANGES |
| --- | --- | --- | --- |
|2.5.4|Communication channel for discussions shall be searched by entering keywords. Those results shall be ranked according to date.|The title and the first post of discussions in the communication channel shall be searched by entering keywords. Those results shall be ranked according to date.|Searching in comment should be out of our scope.|
|2.5.5|The notes belonging to and shared with a user shall be searchable.|The notes belonging to a user shall be searchable.|Searching in shared notes is more complicated than it sounds. Searching in user’s own notes should be enough.|

Here are the _removed_ requirements for **2.5. Search Engine**.

| REQUIREMENT | OLD | REASON|
| --- | --- | --- |
|2.5.3.3|The courses that are similar to those that are taken by the users that the user follows should be ranked higher than other courses.|Too advanced for our project!|

**Comment by ersoykadir** [comment]
## 1.4 Admin
> Here are the changes I propose for 1.4. Admin User requirements:
> 
> Old:
> 
> > 1.4. Admin User
> > 
> > * 1.4.1. Admins shall be able to ban users for inappropriate behaviors.
> > * 1.4.2. Admins shall be able to delete inappropriate comments and articles.
> 
> 1.4. Admin User
> 
> * 1.4.1. Admins shall have access to all account features described in 1.1 except 1.1.1 and 1.1.2.2.
- This looks to complicated to understand. Maybe we can use something like,
  - Admins shall be able to login to and logout of their account, provided that they have valid admin email-password pair.
> * 1.4.2. Admins shall be able to see all user profiles regardless of users' privacy status.
> * 1.4.3. Admins shall be able to view all course contents regardless of courses' privacy status.
> * 1.4.4. Admins shall be able to ban users for inappropriate behaviors.
> * 1.4.5. Admins shall be able to delete inappropriate comments, notes, annotations and course material.
> * 1.4.6 Admins shall be able to utilize the search engine to find specific posts and users.
- These look good.
> * 1.4.7 The system should notify admins when a new report is made.
> * 1.4.8 The system should provide an interface for admins to view and resolve reports.
> 
- I am not sure we will implement report system. Needs to be discussed with team. 
> For the glossary:
> 
> Reporting: The action taken by users to when they see another user behaving inappropriately. The admin users can then view those reports and choose to whether act on them or not and mark the issue as resolved.
> 
> Other related requirements:
> 
> 1.3.15. Users shall be able to report comments, notes, annotations and course material to the admins if they think they are inappropriate.
- Reporting must be discussed.

**Comment by ersoykadir** [comment]
> I had updated the section _2.6 Annotation_, as well as adding 2 new requirements under the section (_1.3. User Actions_) regarding _annotation_ again, on 15 Oct as:
> 
> Requirement ID	Body	Change Type
> 2.6.3	The system shall provide a mechanism such that annotation can be applied to any ~context~ note or course content.	edit
> 2.6.4.	The system shall highlight annotated text portions to emphasize annotation.	addition
> 1.3.6.1.	User shall select a portion of the text to annotate.	addition
> 1.3.6.2.	User should be able to turn on and off annotation visibility.	addition

- This is good. But annotations requirements will probably be updated after next weeks 451 class, since the class context will  be annotations. We shall take notes and update accordingly.
 
For the rest, @bilalcim , @salimtirit , @mertcan-ozkan , @Goko6, @hsuleerkul Thanks for the effort. If you did not updated these on wiki [requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements) page, I think you can and should do now.

@nurlandadashov02 , @yilmaz-burak , It would be awesome if you can go over your parts as soon as possible.

Since the remaining requirements are glossary and non-functional ones, they would be easy and less controversial. So after Annotations and Admin requirements discussed, this issue can be closed.

**Comment by arfakbaba** [comment]
After discussion with group and  revising the meeting notes [#16](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2316-11.10.2022) and [#17](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2317-12.10.2022). Here are the revised requirements for 2.6. Communıcation Channel.

| REQUIREMENT | OLD | NEW | CHANGES |
| --- | --- | --- | --- |
|   2.2.3.| The system should support sharing resources and files.|The system should support sharing image files.|Sharing resources and files is confusing so only sharing image files is enough for us.|
|2.2.2|The system shall provide a discussion section for any type of user inside a course.|The system shall provide a discussion section after end of each chapter for users to comment and discuss about that specific chapter.|The discussion will now be available to the user after the course is over.|

**Comment by nurlandadashov02** [comment]
Minor update for non-functional requirements.
| REQUIREMENT | OLD | NEW | 
| --- | --- | --- | 
| 3.4.1.| The platform shall respond n at most 3 seconds.|The platform shall respond to any request in at most 5 seconds.|

**Comment by ersoykadir** [comment]
Thanks everyone for the effort. Updated requirements can be found [here](https://github.com/bounswe/bounswe2022group3/wiki/Requirements)
