### ISSUE TITLE
Tracking Requirements Wiki Page

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#27]
We should have at least a template of what our requirements will look like. We have distributed each part to team members and assigned different reviewers for those issues.

There should be a table to easily track our state.   

Deadline: 16.03.2022

**Comment by muhammetssen** [comment]
We can use the following table to track requirements.
 
`Completed`: Requirements are prepared and waits for review
`Reviewed` : Reviewer has investigated and gave feedback to assignee or has no feedback and closed the issue.


| Description | Issue | Completed | Reviewed | Added to [Requirements Page](https://github.com/bounswe/bounswe2022group3/wiki/Requirements)
|:---|:---:|:---:|:---:|:---:|
Search Engine | #13 |  ⬜  | ⬜ | ⬜ |
Glossary | #15 |  ⬜  | ⬜ | ⬜ |
Recommendations | #16 |  ⬜  | ⬜ | ⬜ |
Lecturer | #17 |  ⬜  | ⬜ | ⬜ |
Learner | #18 |  ⬜  | ⬜ | ⬜ |
Communication Channel | #21 |  ⬜  | ⬜ | ⬜ |
Annotation | #22 |  ⬜  | ⬜ | ⬜ |
Note Taking | #23 |  ⬜  | ⬜ | ⬜ |
Profile Page | #24 |  ⬜  | ⬜ | ⬜ |
Event | #25 |  ⬜  | ⬜ | ⬜ |

**Comment by hsuleerkul** [comment]
Every task in the table has been completed and requirements document is ready. Here is the
[Requirements Page](https://github.com/bounswe/bounswe2022group3/wiki/Requirements)
