### ISSUE TITLE
Create Initial Infra for backend

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#274]
### Issue

We need to create the barebone backend structure. We should dockerize the project so that we can easily develop locally also. 

### Task(s)

- [x] Dockerize the backend
- [x] Create mongoose connections and simple mongoodb schema using it

### Acceptance Criteria

* Should pass review after all backend team approves the project working. @Goko6  @ersoykadir @furkanakkurt1335 

### Deadline of the issue

19.10.2022 @23.59

### Reviewer

Kadir Ersoy

### Deadline for Review

20.10.2022 @23.59

**Comment by ersoykadir** [comment]
Done, reviewed in meeting.
