### ISSUE TITLE
Tracking Weekly Efforts - Week #2 and Week #3

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#276]
### Issue

All the team members should report their weekly efforts in the wiki. You can find the created page [here #2](https://github.com/bounswe/bounswe2022group3/wiki/451-Week-2-Personal-Efforts) and [here #3](https://github.com/bounswe/bounswe2022group3/wiki/451-Week-3-Personal-Efforts)

### Task(s)

 - [x] Arif Akbaba
- [x] Bilal Aytekin
- [x] Mehmet Gökberk Arslan
- [x] Furkan Akkurt
- [x] Nurlan Dadashov
- [x] Hatice Şule Erkul
- [x] Kadir Ersoy
- [x] Berke Özdemir
- [x] Mertcan Özkan
- [x] Muhammet Şen
- [x] Salim Kemal Tirit
- [x] Burak Yılmaz

### Acceptance Criteria

- Weekly effort of each team member must be documented

### Deadline of the issue

19.10.2022 @23:59

**Comment by yilmaz-burak** [comment]
Everybody wrote their weekly efforts. Thanks everyone!
