### ISSUE TITLE
Meeting Notes Documentation - Mobile Team 19.10.22

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#278]
### Issue

As mobile team, we have done our first meeting on our app's basic ui design and how Flutter works. As the note taker for the meeting I will be documenting its meeting notes. 

### Task(s)

- [x] Cleaning up the notes
- [x] Documenting the notes

### Deliverable(s)

* Mobile Team | Meeting Notes 19.10.22 notes ([link](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%231-19.10.2022-Mobile-Team) is now available!)

### Acceptance Criteria

* Meeting notes should be up and visible on the wiki page and the side bar.

### Deadline of the issue

20.10.22 @20.00

### Reviewer

Salim Tirit

### Deadline for Review

20.10.22 @23.59

**Comment by hsuleerkul** [comment]
I have finished writing the notes and you can see them [here](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%231-19.10.2022-Mobile-Team). As I write them I realized, we did not specified any deadlines. I will discuss this with my teammates and update the notes, adding the deadlines and issue numbers later.

**Comment by salimtirit** [comment]
I read the meeting notes. I think that the only missing thing is that there was a notification tab in the navigation panel on the home page. Other than that it is perfect thank you for your effords.

**Comment by hsuleerkul** [comment]
Thank you for reviewing! I updated the notes and added `Notifications`.
