### ISSUE TITLE
Documenting Meeting Notes #3, 13.03.2022

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#28]
Weekly meeting notes should be documented under relevant Wiki Page.
Deadline: 15.03.2022, 10.00 AM
@ersoykadir

**Comment by ersoykadir** [comment]
Meeting [Notes#3](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%233-13.03.2022) is documented.
