### ISSUE TITLE
Editing Requirements System- Profile Page

### ISSUE THREAD

**Issue by mertcan-ozkan** [bounswe/bounswe2022group3#31]
The Requirements Systems- Profile Page [draft](https://github.com/bounswe/bounswe2022group3/wiki/Requirements) should be eddited based on the feedback of [questions](https://github.com/bounswe/bounswe2022group3/wiki/Questions-to-Customer) given in the PS section in 16.03.2022 . Also the previous [issue](https://github.com/bounswe/bounswe2022group3/issues/24) regarding this topic had feedback from the reviewer of that issue. Those feedbacks will be addressed too.
Deadline : 23.03.2022
Reviewer:  @muhammetssen

**Comment by mertcan-ozkan** [comment]
Based on the Ps meeting in 16.03.2022 and [feadbeck](https://github.com/bounswe/bounswe2022group3/wiki/Questions-to-Customer) , the following topics will be added or changed:

1-There will not be a grading mechanism for the courses but students will collect a badge for their success.
2-Student will be able to give feedback to the teachers by giving them a review between 1 to 5.
3-Achivement badges will be predifned by the system but additional badges can be created by the teacher.
4-Interests -there will be categories defined by the system and students will choose from this category to specify their interests' .
5-A course may hold quizes. The monitorıng system will show the users how many quizes that they have attended.
6-Profiles can be either public or private. 
7-A user will be able to block another user.

**Comment by mertcan-ozkan** [comment]
The following changes are made:
Learner Profile 
Achivements:
 2.1.1.2.2.2 changed
2.1.1.2.2.3 and its subsections added
2.1.1.2.2.4  added
2.1.1.2.2.5 added
Interests:
2.1.1.2.3.1.  changed
2.1.1.2.3.2 and its sub sections added
Activities:
2.1.1.2.4.2. changed 
2.1.1.2.4.3.5 added
Monıtoring:
2.1.1.2.5.1.3 added
Privacy (2.1.1.4.):
entire section added
Following 
2.1.1.3.2.1.5. added
2.1.1.3.2.1.6. added

**Comment by muhammetssen** [comment]
Thanks for the detailed report, looks good to me! Thanks
