### ISSUE TITLE
[Mobile] Backend Connection For Course Page

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#319]
### Issue

After #318 we need to get the necessary data from the backend. I will use services that were written by @muhammetssen in #316. I will also have mock services to use in case of need. 

### Task(s)

Will be completed...

### Acceptance Criteria

* Being able to get all data from the backend for the course page.

### Deadline of the issue

30.10.2022 @23.59

### Deadline for Review

31.10.2022 @23.59

**Comment by muhammetssen** [comment]
Closed by #318
