### ISSUE TITLE
Reviewing of the Weekly Efforts #3

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#33]
All the team members should report their weekly efforts in the wiki. You can find the created page [here](https://github.com/bounswe/bounswe2022group3/wiki/Week-3--Personal-Efforts) 

- [x] Arif Akbaba
- [x] Bilal Aytekin
- [x] Mehmet Gökberk Arslan
- [x] Nurlan Dadashov
- [x] Hatice Şule Erkul
- [x] Kadir Ersoy
- [x] Ahmet Kudu
- [x] Muhammet Şen
- [x] Bengisu Takkin
- [x] Burak Yılmaz
- [x] Salim Kemal Tirit
- [x] Mertcan Özkan

Deadline: 23.03.2022, 4.00 PM

**Comment by hsuleerkul** [comment]
All members have written their efforts in this [page](https://github.com/bounswe/bounswe2022group3/wiki/Week-3--Personal-Efforts).
