### ISSUE TITLE
Update Requirements for Milestone 1

### ISSUE THREAD

**Issue by Goko6** [bounswe/bounswe2022group3#330]
### Issue

Requirements need some updates based on the changes requested by the customer.

### Task(s)

- [x] Review the changes that are stated in the [meeting notes 10/30](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2319-30.10.2022)
- [x] Update the requirements

### Deliverable(s)

* Updated requirements

### Acceptance Criteria

* The updates should be in line with the decisions we made during the team meeting

### Deadline of the issue

31.10.2022 15.00

### Reviewer

Gökberk Arslan

### Deadline for Review

31.10.2022 23.00

**Comment by Goko6** [comment]
I have exchanged the new words with the old ones and added 3 new requirements that were specified in the [meeting notes](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2319-30.10.2022).

**Comment by ersoykadir** [comment]
Well done!
