### ISSUE TITLE
Tracking Weekly Efforts - Week #4

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#334]
### Issue

All the team members should report their weekly efforts in the wiki. You can find the created page [here](https://github.com/bounswe/bounswe2022group3/wiki/451-Week-4-Personal-Efforts) 

### Task(s)

 - [x] Arif Akbaba
- [x] Bilal Aytekin
- [x] Mehmet Gökberk Arslan
- [x] Furkan Akkurt
- [x] Nurlan Dadashov
- [x] Hatice Şule Erkul
- [x] Kadir Ersoy
- [x] Berke Özdemir
- [x] Mertcan Özkan
- [x] Muhammet Şen
- [x] Salim Kemal Tirit
- [x] Burak Yılmaz

### Deliverable(s)

* ...
* ...
* ...

### Acceptance Criteria

- Weekly effort of each team member must be documented

### Deadline of the issue

02.11.2022 @23:59

**Comment by yilmaz-burak** [comment]
Everyone wrote their effors. Thanks everyone!
