### ISSUE TITLE
Tracking statuses of scenarios and mockups

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#34]
## Description
We will create 3 different scenarios in order to understand and validate requirements. Each scenario will have a persona, preconditions, desired goal(s) and acceptance criteria. Moreover, we will prepare mockups (both for mobile and web) to see the project from a customer's eyes.

## Current Status
| Name |Issue  | Scenario | Web Mockup | Mobile Mockup |
|:-:|:-:|:-:|:-:|:-:|
|Scenario 1 | #37 #39 #40| ✅   | ✅   | ✅  |
|Scenario 2 |  #44 #46 #47 #48| ✅   | ✅  | ✅   |
|Scenario 3 | #38 #41 #42 #45| ✅  | ✅   | ✅  |

**Comment by mertcan-ozkan** [comment]
Scenario 1- Scenario , Web Mockup, Mobile Mockup are all completed.

**Comment by yilmaz-burak** [comment]
[Scenerio 3 - Note Taking](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-3) both mockups and scenario are completed
