### ISSUE TITLE
Customer Milestone Feedbacks

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#342]
### Issue

We have been through first milestone.  I was the note-taker during the presentation and I will document the feedbacks from customer for later use.

### Task(s)

- [x] Clean up the notes from the milestone.
- [x] Document them on wiki.

### Deliverable(s)

* Wiki page of Customer Milestone 1 feedback.

### Acceptance Criteria

* Customer Milestone 1 feedbacks must be delivered on wiki page.

### Deadline of the issue

02.11.2022

**Comment by ersoykadir** [comment]
Main headlines:
- Organizing Information
  - There can be tons of content, notes and discussions headlines. We must handle the organization and ordering of these on the learning spaces. Especially on mobile, since we do scrolling down content, we must decide where it will stop scrolling or will it show each content existing. For both mobile and web, we may do ordering, filtering and searching among these content, discussion and notes. 
- Activity Stream
  - What has happened in my spaces while I was away from the app? We can show user an activity stream to depict the ongoing events and popular contents and discussions etc. 
  - Also notifications should be handled well, to show the user how people reacted to stuff related to him etc. To keep the user in contact with the platform.
- Font and Text Colors
  - Some of the content and note headers were not readable due to colors. We might need to pick contrasting colors to avoid this.
- Automated Interests
  - Instead of making users choose interest tags, we can compose the list of interests from the user's joined spaces and especially the spaces that they contributed in.
- Contributions on Profile
  - We can showcase contributions done by user on their profile. Number of content uploaded, number of events organized etc.
- Labeled Feedbacks
  - We may have different feedback evaluations so that instead of giving a single number for feedback like 5, users can elaborate this feedback by giving content quantity=3 but content quality=5 and community interaction=4 etc.

**Comment by furkanakkurt1335** [comment]
I can also add this: while browsing, unfollowing a topic can be useful. Showing a topic again and again, and no interaction from the user may indicate disinterest also.

**Comment by ersoykadir** [comment]
> I can also add this: while browsing, unfollowing a topic can be useful. Showing a topic again and again, and no interaction from the user may indicate disinterest also.

We can make an not interested system for automated interests. Will note this as well

**Comment by ersoykadir** [comment]
Feedbacks are visible on wiki, [here](https://github.com/bounswe/bounswe2022group3/wiki/Customer-Milestone-1-Feedbacks)
