### ISSUE TITLE
[mobile] - Connecting Login and Registration pages to backend

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#343]
### Issue

@bilalcim has implemented the UI for login and registration pages in #339. We are ready to connect those pages to our backend server. Note that the required functions are already implemented in the UserService class.

### Task(s)

- Completing login and registration forms  
- Validating input data
- Calling the UserService functions:
  -  If successful:
      1. Notify the user by showing a pop-up
      2. Restart the app - You can do it by navigating to the intro view. Do not forget to clear the navigation stack 
  - If not:
      1. Show the error message to the user

### Deliverable(s)

-

### Acceptance Criteria

- Being able to login
- Being able to sign up
- Seeing the error message(s) during the flow

### Deadline of the issue

12.11.2022 23:59

**Comment by bilalcim** [comment]
Closed by #377.
