### ISSUE TITLE
Milestone 2 objectives

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#346]
### Issue

We have officially gone over milestone 1. Now we need to make plans for the next Milestone. Here I list some of the suggested stuff on the last meeting for future plans. I elaborately write backend related objectives and write my feedbacks for other teams.
`I would like every team member to add their related feedbacks and criticism as comment for both their teams and other teams as well.` We can create a total objectives list this way.

I would suggest that we also gather first meeting decisions from each team for coordination under this issue. So, this issue must be updated after the first team meetings and then closed.

### Task(s)

- [ ] Making an outline of milestone 2 plan.

### Deliverable(s)

* Outline of Milestone 2 plan.

### Acceptance Criteria

* First in-team meetings' action items must be added.

### Deadline of the issue

11.11.2022

**Comment by ersoykadir** [comment]
### Feedbacks
- Backend
  - Namings should be updated for backend like Course->Learning Space.
  - Unit Testings must be completed before moving on.
    - Problems on enrollment must be resolved first.
    - Issues on user profile endpoint must also be resolved. We need to add detailed fields for profile.
- Frontend
  - Homepage/My courses uses same api request, latter needs to use get enrolled courses endpoint. This will be updated at backend and needs to get adjusted on front after that.
  - It could be nice if our home page, course detail page and profile pages can be prettied up
- Mobile
  - Sign-up/Login pages needs to be added.
  - Profile page might get connected to backend.
### For the next milestone:
  - Event-geolocation 
  - Resources must be handled
  - Note taking-annotation
  - We might want to open a development branch.

**Comment by salimtirit** [comment]
### Feedbacks
- Backend
  - There should be some script to populate the database to test in the frontend and mobile. 
  - There should be more communication with the team members of frontend and mobile teams.
- Frontend
  - There should be a domain name for our application. 
  - Work with the mobile team on the design.
  - Most parts need to be connected to the backend and not static.
- Mobile
  - The email confirmation link should redirect our application.
  - Work with the frontend team on the design.
  - Most parts need to be connected to the backend and not static.
  - We need to work together more. 
  - Fix the color problem mentioned in [customer milestone 1 feedback](https://github.com/bounswe/bounswe2022group3/wiki/Customer-Milestone-1-Feedbacks)
### For the next milestone:
  - Uploading profile pictures and editing the profile page should be implemented.
  - Generating content should be implemented. This content may be uploading documents to the learning space, creating meetings, or commenting on discussions.

**Comment by ersoykadir** [comment]
These topics discussed on this [meeting](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2320-08.11.2022).

**Comment by ersoykadir** [comment]
The objectives for M2 is discussed on both [group meeting](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2320-08.11.2022) and [back](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%234-BackEnd-Team) and [front](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%233-Front-End-Team) teams have met up and planned w.r.t to those decisions.
