### ISSUE TITLE
Meeting notes for 08.11.2022

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#347]
### Issue

We had a meeting during lab hours. We talked about the first milestone and we did some plans for the second milestone. We also talked with our TA. Notes of these meetings should be documented on the wiki page. 

### Task(s)

- [x] Clear the notes taken during the meeting.
- [x] Document them on the wiki.

### Deliverable(s)

*  Meeting notes will be [here](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%2320-08.11.2022)

### Acceptance Criteria

* Meeting notes should be up and visible on the wiki.

### Deadline of the issue

09.11.2022 @23.59

### Reviewer

Şule Erkul

### Deadline for Review

10.11.2022 @23.59

**Comment by ersoykadir** [comment]
Well done!
