### ISSUE TITLE
Create a script for mock data creation in database

### ISSUE THREAD

**Issue by furkanakkurt1335** [bounswe/bounswe2022group3#349]
We need to create a script for populating / mocking our databases. MongoDB mock data creation can be done using the _mongosh_ command-line tool. I think writing a single JavaScript file will be good for this. For reference: https://www.mongodb.com/docs/mongodb-shell/write-scripts/#execute-a-script-from-within-mongosh

**Comment by ersoykadir** [comment]
We will gather mock data at [here](https://humble-bull-0d3.notion.site/Database-28935d374a444312b002bd0e35f9765d). Then we will have a script for collecting the mock data and writing it to DB

**Comment by ersoykadir** [comment]
This is avoided for now, no need to keep it open. Hopefully, after creating the create endpoints, data will be accumulated and we won't need any mock data creation script.
