### ISSUE TITLE
Backend Team Meeting #4

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#353]
### Issue

We will have a meeting to plan this week with backend team. Agenda:
- Backend naming conventions change
- Unit tests for all
- Enrollment, course
- Topic/Comment/Resource create, update endpoints
- Profile needs all fields implemented
- Research
    - Annotation
    - Geolocation
- Database population
- Development branch

### Task(s)

- [x] Have a meeting for week 6.
- [x] Document the meeting notes.

### Deliverable(s)

* Wiki link for meeting notes

### Acceptance Criteria

* Meeting notes documented on wiki.

### Deadline of the issue

10.11.2022 @23.59

**Comment by furkanakkurt1335** [comment]
Meeting notes started [here](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%234-BackEnd-Team).

**Comment by ersoykadir** [comment]
- Backend naming conventions change
  - @yilmaz-burak
- Research
    - Annotation - @ersoykadir 
    - Geolocation - @furkanakkurt1335 
- Profile endpoint fields detailed
  - @Goko6 
 ### These will be done within this week 
- Unit tests for all
- Enrollment, course
  - Enrollment must be unique (user, course pair)
  - Must have a regex option for searching.
  - Course -> Space
- Create Topic/Comment/Resource should be
  - handled such that they will be connect to their upper objects `Space/Discussion/Topic`
- Database population
- Development branch

**Comment by ersoykadir** [comment]
Meeting notes documented [here](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%234-BackEnd-Team).
