### ISSUE TITLE
[Frontend] Making frontend application gdpr compliant

### ISSUE THREAD

**Issue by berkeozdemir2016400246** [bounswe/bounswe2022group3#360]
### Issue

Users shall agree to the Terms of Service and Privacy Policy while registering. (see [requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements) 3.3.2)

### Task(s)

Registration page needs a checkbox that requires the user to check it before continuing. Then it's value should be added to the user/register enpoint's request model

### Deliverable(s)

Frontend code adressing the issue

### Acceptance Criteria

Well written code that is reviewed by peers

### Deadline of the issue

13.11.2022

### Reviewer

Berke Özdemir

### Deadline for Review

13.11.2022

**Comment by berkeozdemir2016400246** [comment]
Issue can be tracked on #362

**Comment by ersoykadir** [comment]
@berkeozdemir2016400246 Could you take a look at #352 for backend connection of /register, I have added gdpr agreement check, so you can may need to change the payload for backend /register request
