### ISSUE TITLE
[Mobile] Problem In Profile Page

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#363]
### Issue

There is a problem with the profile page on the mobile page when it is used horizontally. Here is a screenshot of the problem:
![WhatsApp Image 2022-11-16 at 22 17 30](https://user-images.githubusercontent.com/64011660/202273621-38eb79a3-da27-49ab-8979-ecd06bd10229.jpeg)

### Task(s)

- [x] Fix the overflow problem on the profile page.
- [x] Report the reason for the problem here for the other members of the mobile team to learn from it

### Deliverable(s)

* Profile page
* Reason comment

### Acceptance Criteria

* Properly working profile page horizontally

### Deadline of the issue

19.11.2022 @23.59

### Reviewer

Salim Tirit

### Deadline for Review

20.11.2022 @23.59

**Comment by hsuleerkul** [comment]
### Explanation for Mobile team
After trying to fix this problem for an unreasonable amount of time, I came up with a quick solution to this. Which is NOT allowing user to use bucademy horizontally! If we decide horizontal view is important then we can try to come up with a permanent solution for this.
