### ISSUE TITLE
[Backend] Update on Chapter and Content models

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#367]
### Issue

We will change `chapter` to `topic` and `content` to `resource`. Both schemas and endpoints will be updated for the name change.

### Task(s)

- [ ] Update naming conventions for `chapter` and `content`.

### Deliverable(s)

* PR for related update.

### Acceptance Criteria

* PR is reviewed and merged.

### Deadline of the issue

19.11.2022 @23.59

**Comment by furkanakkurt1335** [comment]
This had been implemented in #372.
