### ISSUE TITLE
Tracking Weekly Efforts - Week #7

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#369]
### Issue

All the team members need to keep track of their weekly efforts. You can find the created page [here](https://github.com/bounswe/bounswe2022group3/wiki/451-Week-7-Personal-Efforts)

### Task(s)

- [x] Arif Akbaba
- [x] Bilal Aytekin
- [x] Mehmet Gökberk Arslan
- [x] Furkan Akkurt
- [x] Nurlan Dadashov
- [x] Hatice Şule Erkul
- [x] Kadir Ersoy
- [x] Berke Özdemir
- [x] Mertcan Özkan
- [x] Muhammet Şen
- [x] Salim Kemal Tirit
- [x] Burak Yılmaz

### Deliverable(s)

* The [451 Week 7 Personal Efforts](https://github.com/bounswe/bounswe2022group3/wiki/451-Week-7-Personal-Efforts) page.

### Acceptance Criteria

* Weekly effort of each team member must be documented

### Deadline of the issue

22.11.2022 @15:00

### Reviewer

@bilalcim

**Comment by bilalcim** [comment]
Thanks, everyone, great work!
