### ISSUE TITLE
[Backend] Implementation of Discussion endpoint

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#370]
### Issue

We need to update our discussion and comment endpoints w.r.t #352.

### Task(s)

- [ ] Update schemas and endpoints according to #352 for discussion and comment.

### Deliverable(s)

* PR for related update.

### Acceptance Criteria

* PR is reviewed and merged.

### Deadline of the issue

25.11.2022 @23.59

**Comment by yilmaz-burak** [comment]
This is resolved by #385. Closing.
