### ISSUE TITLE
Mobile Mockup for Scenario #3

### ISSUE THREAD

**Issue by bilalcim** [bounswe/bounswe2022group3#41]
A mobile mockup shall be prepared for [Scenario #3](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-3) using the template that is prepared in [Issue #32](https://github.com/bounswe/bounswe2022group3/issues/32).

**Comment by bilalcim** [comment]
Mockup is prepared and added to page [Scenario #3](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-3). Waiting for review.

**Comment by muhammetssen** [comment]
We reviewed the mockup in a team meeting. Everything looks good!
