### ISSUE TITLE
Writing Acceptance Criteria of Scenario#2

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#44]
The matching between requirements and scenario 2 (Acceptance Criteria) needs to be done.

**Deadline:** 22.03.2022 22.00

**Comment by hsuleerkul** [comment]
First draft of acceptance criteria is written below. It needs to be reviewed.

## Acceptance Criteria
- 1.2.1. Learners shall enroll to any course s/he wants to
- 1.2.5. Learners shall be able to use communication tools for asking
- 2.2.1. System shall provide an interface such that users can ask and answer questions.
- 2.2.2. System shall provide a discussion section for any type of user.
- 2.2.2.1. System should support replying, mentioning and threaded messages.

**Comment by muhammetssen** [comment]
We could add the following requirement since user uploads screenshots.
2.2.3. System should support sharing resources and files

**Comment by muhammetssen** [comment]
Added specified requirement and reviewed all criteria with the team.
