### ISSUE TITLE
Mobile Mockup for Scenario #2

### ISSUE THREAD

**Issue by Goko6** [bounswe/bounswe2022group3#46]
A mockup for a mobile user shall be prepared for [Scenario #2](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-2) according to the template in [Issue #32](https://github.com/bounswe/bounswe2022group3/issues/32).

**Comment by Goko6** [comment]
A draft for mobile mockup is created and needs further review.

**Comment by muhammetssen** [comment]
Looks great! Thanks
