### ISSUE TITLE
Creating Git Repository Research Page

### ISSUE THREAD

**Issue by arfakbaba** [bounswe/bounswe2022group3#5]
Every group members should do research about Git Repositories. Their research should revise and be gathered in Research page. 
- [x] [Arif Akbaba](https://github.com/bounswe/bounswe2022group3/wiki)
- [x] [Bilal Aytekin](https://github.com/bounswe/bounswe2022group3/wiki)
- [x] [Mehmet Gökberk Arslan](https://github.com/bounswe/bounswe2022group3/wiki/Mehmet-G%C3%B6kberk-Arslan)
- [x] [Nurlan Dadashov](https://github.com/bounswe/bounswe2022group3/wiki/Nurlan-Dadashov)
- [x] [Hatice Şule Erkul](https://github.com/bounswe/bounswe2022group3/wiki/Hatice-%C5%9Eule-Erkul)
- [x] [Kadir Ersoy](https://github.com/bounswe/bounswe2022group3/wiki/Kadir-Ersoy)
- [x] [Ahmet Kudu](https://github.com/bounswe/bounswe2022group3/wiki)
- [x] [Muhammet Şen](https://github.com/bounswe/bounswe2022group3/wiki)
- [x] [Bengisu Takkin](https://github.com/bounswe/bounswe2022group3/wiki)
- [x] [Burak Yılmaz](https://github.com/bounswe/bounswe2022group3/wiki)
- [x] [Salim Kemal Tirit](https://github.com/bounswe/bounswe2022group3/wiki)
- [x] [Mertcan Özkan](https://github.com/bounswe/bounswe2022group3/wiki) 

Deadline: 07.03.2022

**Comment by nurlandadashov02** [comment]
All team members added their favorite github repos.
