### ISSUE TITLE
Adding User Goals to Scenario #3 

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#52]
We need to add goals section to [Scenario #3](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-3)
 for a complete scenario implementation.
Deadline: 29.02.2022

**Comment by yilmaz-burak** [comment]
[User Goals](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-3#user-goals) section added just after Persona. Now awaits review.

**Comment by hsuleerkul** [comment]
Both I and @nurlandadashov02  reviewed the new user goals, they are informative. Therefore, this issue is closed.
