### ISSUE TITLE
Adding User Goals for Scenario#1

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#53]
User goals for [scenario#1](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-1) is missing, will be written and added.

Deadline: 27.03.2022

**Comment by ersoykadir** [comment]
User goals section is [added](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-1#user-goals), awaiting review.

**Comment by nurlandadashov02** [comment]
User goals have been reviewed.
