### ISSUE TITLE
Adding a privacy section to the requirements

### ISSUE THREAD

**Issue by bilalcim** [bounswe/bounswe2022group3#54]
I will add a separate section for privacy to the [requirements page.](https://github.com/bounswe/bounswe2022group3/wiki/Requirements)
**Deadline:** 28.03.2022 23.59

**Comment by bilalcim** [comment]
I have detailed the existing privacy section.

**Comment by hsuleerkul** [comment]
I edited 3.3.6. to correct its meaning and resolve any ambiguities. Other than that no changes were needed.
