### ISSUE TITLE
Editing Glossary of the Requirements

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#56]
After team members are done with revising the [Requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements), the glossary should be edited accordingly and ambigious terms need to be updated.

**Deadline:** 28.03.2022 23.59

**Comment by hsuleerkul** [comment]
I revised the glossary and made major changes on terms " **Learner,** **Lecturer,** and **Poll**".

**Comment by nurlandadashov02** [comment]
Reviewed, some minor corrections were made
