### ISSUE TITLE
Revising User Requirements

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#60]
User requirements shall be revised according to the criticisms we have received and the decisions that we have arrived at in last week's customer meeting. Meeting notes can be seen [here](https://github.com/bounswe/bounswe2022group3/wiki/Customer-Meeting-Notes-%231-23.03.2022). Also, this issue is planned in the weekly meeting whose notes can be seen [here](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%235-25.03.2022). This issue can be considered as regulation on #17 and #18

**Comment by Brunettow** [comment]
DRAFT OF THE NEW VERSION 

1.2. User
> 1.2.1. Profile (described in 2.1.).
>> 1.2.1.1. Users shall have a profile exclusive for themselves.
>> 1.2.1.2. Users should be able to store their personal information in their profile.
>> 1.2.1.3. Users shall be able to modify their personal information if needed.
>> 1.2.1.4. Users shall be able to choose if their profile will be public or private.
>> 1.2.1.5. Users shall be able to follow other users.
>> 1.2.1.6. Private profiles shall be visible to only followers.
>> 1.2.1.7. Public profiles shall be visible to all users.
>> 1.2.1.8. Users should have their interests and their knowledge in their profile page.
>> 1.2.1.9. Users should have their activities and achievements in their profile page.
>> 1.2.1.10. Users shall be able to block other users.
>> 1.2.1.11. Users shall be able change their password via email confirmation.
>> 1.2.1.12 Users shall be able to delete their account.
> 1.2.2 Registration 	
>> 1.2.2.1. Users shall be able to register either using a valid and unique email address, a username, and a secure password as defined in the security section or using their facebook, twitter, google account.
> 1.2.3. Authentication
>> 1.2.3.1 Users shall confirm their email addresses via clicking to the link sent in the confirmation email.
> 1.2.4 Log In
>> 1.2.4.1. Users shall be able to log into their account using their email and password combination or via using their facebook, twitter, google account.
>> 1.2.4.2. If a user enters a wrong password three times while logging in, they will need to reset their password using their email.
> 1.2.5. User Actions
>> 1.2.5.1. Users shall be able to use the communication channel (described in 2.2.)
>> 1.2.5.2. Users shall be able to use the note taking feature (described in 2.3.)
>> 1.2.5.3. Users shall be able to use the search engine (described in 2.5.)
>> 1.2.5.4. Users shall be able to use the annotation features (described in 2.6.)
>> 1.2.5.5. Users shall enroll to any course s/he wants to.
>> 1.2.5.6. Users shall be able to open a course in any subject, they don’t need to prove any document regarding their experience on the topic. The user becomes the lecturer of the course s/he opened.
>> 1.2.5.7. Lecturers shall be able to create polls, allowed to be filled by the students enrolled in their course. The anonimity and/or the obligation of the poll shall be decided by the lecturer and declared to the students.
>> 1.2.5.8. Lecturers shall be able to organize and schedule events. The scope of the event depends on the lecturer's initiative. It can be public or private, face to face or online, free or needs a fee to enter. 
>> 1.2.5.9. If there are not enough participants, the lecturer has the right to cancel the event.

**Comment by Brunettow** [comment]
May the profile page part be moved to the user part

**Comment by Brunettow** [comment]
Lecturer and Learner parts can be unified under a single User part.

**Comment by yilmaz-burak** [comment]
Seems that you unified common requirements of lecturer and learners under Users, which was the main goal. LGTM! Thanks!
