### ISSUE TITLE
Setting up LucidChart for Teamwork

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#62]
We need a lucidchart environment to work on diagrams together. Assignee will open the diagram and invite every team member.

Deadline : 02.04.2022 12:00

**Comment by yilmaz-burak** [comment]
Project is initiated in [here](https://lucid.app/lucidchart/31bd815c-fbc1-412b-a38e-72d806836d55/edit?invitationId=inv_d3924d40-f3c4-4c35-8c77-e8a466a7359a). Members can start editing the diagrams.
