### ISSUE TITLE
Revising Privacy requirements

### ISSUE THREAD

**Issue by nurlandadashov02** [bounswe/bounswe2022group3#64]
There are two Privacy sections in [Requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements), one in System requirements, the other in Non-functional requirements. All privacy requirements will be moved to non-functional requirements. In system requirements, only the "A user shall be able to change privacy settings." requirement shall be written. Current privacy requirements in the system section describe the visibility of the profile page, not interactions with the profile page. Thus, they are non-functional.

Deadline 03.04.2022 23.59

**Comment by Brunettow** [comment]
First draft is added [here](https://github.com/bounswe/bounswe2022group3/wiki/Requirements-(New-Version))
What is changed?
- Lecturer and Learner parts are deleted
- Search engine part moved to the system requirements
- Changing requirements that contains phone (We decided to not use any operations via phones.)

What can be changed?
- Profile part in system requirements and in user can be reviewed and can be unified.

**Comment by nurlandadashov02** [comment]
The following changes were made:

## System Requirements
### 2.1. Profile Page 
....
* 2.1.4. Privacy
    * 2.1.4.1. Users shall be able to change privacy settings. (visibility of their profile page to other users)

### 3.3. Privacy
...
* 3.3.6. The system shall have two options for the visibility setting of a user profile:
    * 3.3.6.1. Public Profile: The system shall allow other users to see the user's profile if the user opts to choose the public profile option.
    * 3.3.6.2. Private Profile: System shall not allow other non-following users to see the user's profile if the user opts to choose the private profile.
    * 3.3.6.3. Additionally, users blocked by another user shall be prevented to interact with the user who blocked them and both parties shall not view any page related to each other.

**Comment by hsuleerkul** [comment]
I have given feedback about some phrases grammar to Nurlan. He made the changes. This issue is now resolved.
