### ISSUE TITLE
Use Case - Create Poll Diagram under Manage Course

### ISSUE THREAD

**Issue by yilmaz-burak** [bounswe/bounswe2022group3#66]
According to our [meeting notes](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%236-01.04.2022), `Create Poll` section under Manage Course diagram shall be drawn. 
Use case will encompass what the system does from the point of the user using it. It should encompass fundamental functionalities of Creating Poll feature. In the end, viewers should gain a perspective as to how the polling system works.

Fundamentals:
* [x] Poll Description --> Body and Title
* [x]  Start and End Dates
* [x]  Select Poll Mode
* [x]  Set Possible Answers

Deadline: 03.04.2022 - 23.59

**Comment by yilmaz-burak** [comment]
First draft for `Create Poll` subsection has been created.
Unfortunately, there seems to be a lack of explanation of polls in our requirements. That will be revised in the next meeting.

![image](https://user-images.githubusercontent.com/46003469/161472624-085c74db-8a06-48e3-aa2c-6e4ee81deef7.png)

After the review in the meeting, this structure may be revised.

**Comment by yilmaz-burak** [comment]
We might want to remove set Start Date since it could mean scheduling an event. Should be discussed in the meeting, might lead to removal of the field.

**Comment by muhammetssen** [comment]
1. I could not understand what you mean by `it could mean scheduling an event`. 
2. I think that merging polls with quizes will create nothing but cumbersome in the long run. Poll should be about getting a basic input for a simple question from the user. In my opinion, we cannot have a quiz structure under this description.
3. Lifespan of a poll can be configured by providing a duration, like 24 hours, instead of specifying start and end dates separately.
4. There should be a case to view the results of a poll/quiz.

**Comment by yilmaz-burak** [comment]
According to the reviews in the meeting and [Discussion Notes](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%237-04.04.2022), made the relevant changes. Will be reviewed in the next meeting again.


![image](https://user-images.githubusercontent.com/46003469/161807935-fe3fc911-f794-4d69-9485-8b6917696bb7.png)

**Comment by yilmaz-burak** [comment]
Added a small action item to user, so that they can attend the polls created.
![image](https://user-images.githubusercontent.com/46003469/161815326-9ea6b52e-1746-4767-a4f5-ecc70bef9c73.png)

**Comment by yilmaz-burak** [comment]
Seemed okay in the meeting, closing the issue.

**Comment by yilmaz-burak** [comment]
Requirements covered in this use case:

* 1.3.8.1. Lecturers shall be able to create polls, allowed to be filled by the students enrolled in their course. The anonimity and/or the obligation of the poll shall be decided by the lecturer and declared to the students.
* 1.3.8.2. Lecturers shall be able to organize and schedule events. The scope of the event depends on the lecturer's initiative. It can be public or private, face to face or online, free or needs a fee to enter.
