### ISSUE TITLE
Revising the Requirements - Checking the use of Language

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#73]
In [customer meeting notes](https://github.com/bounswe/bounswe2022group3/wiki/Customer-Meeting-Notes-%232-30.03.2022), the need for unambigious and grammatically correct language use is mentioned. For this reason, I will read the requirements and make the needed changes to improve the understandability of the [Requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements)

**Deadline:** 05.04.2022 10.00

**Comment by hsuleerkul** [comment]
We talked about this issue, and decided to extend its deadline.
**New** **Deadline:** 08.04.2022 20.00

**Comment by hsuleerkul** [comment]
New terms should be added to the Glossary. They are:
 - Admin user
 - Topic
 - Feedback
 - Comments
 - Chapter
 - Course Content
 - Rating

**Comment by hsuleerkul** [comment]
Grammar corrections are done. The following are edited to suit the meeting notes [6](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%236-01.04.2022), [7](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%237-04.04.2022) and [8](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%238-05.04.2022).

- 2.1.2.7. Feedback Section
   - 2.1.2.7.2. Feedback section shall contain a review point between one to five for each course a lecturer gives.
       - 2.1.2.7.2.1. The review point shall be the avarage of reviews given by the learners taking the course of the lecturer. 

-> changed to:

- 2.1.2.7. Rating
   - 2.1.2.7.1. System shall keep a rating point between one to five for each user that is a lecturer.
      - 2.1.2.7.2.1. The rating point shall be the average of the ratings of the courses that user gives.

- 2.1.3.2. System shall allow the user to see the following features of a profile: achievements, monitoring, feeback section, interests, knowledge, bio, activities.

-> changed to:

- 2.1.3.2. System shall allow a follower of a user to see the following features of a profile: achievements, monitoring, interests, knowledge, bio, activities.

2.2.2. System shall provide a discussion section for any type of user .

-> changed to:

- 2.2.2. System shall provide a discussion section for any type of user inside a course.

**Comment by hsuleerkul** [comment]
Feedback section should be added to the System requirements as discussed in the [meeting 9](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%239-09.04.2022).

**Comment by muhammetssen** [comment]
Feedbacks may have a text to convey the thoughts of the users, though adding text is optional. The fundamental field of a feedback is the score that will be given over 5. Definition in the glossary can be more explanatory.
       `A rating and a text consisting of thoughts of enrolled learners’  about that course.`
Thanks!

**Comment by hsuleerkul** [comment]
About the` feedback` functionality mentioned above, I decided to add another article into [1.3 User Actions](https://github.com/bounswe/bounswe2022group3/wiki/Requirements#user-requirements) section. It is the following : 

`1.3.12. Users shall be able to give feedback consisting of a cumpulsory rating point between 1-5 and an optional text explaining their thoughts to the classes they have enrolled. `

@muhammetssen, I believe this article explains the points you have emphasized.

**Comment by muhammetssen** [comment]
Yeap, it totally does! Thanks

**Comment by hsuleerkul** [comment]
Thanks for the feedback. The article is added to the [Requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements), therefore this issue is closed.
