### ISSUE TITLE
Use Case Diagram - Create Content

### ISSUE THREAD

**Issue by Brunettow** [bounswe/bounswe2022group3#75]
According to the [meeting notes](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%236-01.04.2022), Add content section under the Manage Course diagram shall be prepared. This use case shall describe how a lecturer add a content such as lecture videos.

Deadline: 03.04.2022 - 23.59
Reviewer: @yilmaz-burak

**Comment by Brunettow** [comment]
It is decided to add the parts to diagram such that;
- Add Title
- Add Description
- Add Picture
- Add Video

Also, delete contant and edit content can be added to the diagram.

**Comment by Brunettow** [comment]
The draft of the create content diagram:
![image](https://user-images.githubusercontent.com/63921045/161451955-c492aa1f-5475-49f8-b6d7-f71442c9c9ff.png)

**Comment by hsuleerkul** [comment]
While doing the diagram of `Achievements`, I realized that we mentioned in [Requirements](https://github.com/bounswe/bounswe2022group3/wiki/Requirements) that there are some checkpoints in courses but haven't specified their features. I think that we can add a variable, `isCheckpoint` as an example, that specifies if a user completes this content he/she should gain a badge.

**Comment by yilmaz-burak** [comment]
I don't really understand why this is linked to `Update Profile Page` module. Surely, it is linked to course management but I cannot see the relevance.

**Comment by muhammetssen** [comment]
> I don't really understand why this is linked to `Update Profile Page` module. Surely, it is linked to course management but I cannot see the relevance.

It is not connected to `User Profile Page`, it just a very unlucky arrow 😿. I placed it in a shorter route, problem solved.

**Comment by muhammetssen** [comment]
>I think that we can add a variable, isCheckpoint as an example, that specifies if a user completes this content he/she should gain a badge

We do not have specified requirements for progress in a course. This is integrated with many other classes so we need to start working on it right awayr.
- As @hsuleerkul mentioned, some videos and lectures of a course can be marked as `isCheckpoint`
- Another indicator can be `Number of videos watched / number of all videos`
- We can count the quizes as `completed` and `not completed`

**Comment by Brunettow** [comment]
I changed the diagram structure according to following suggestions from the [meeting #7](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%237-04.04.2022).
- Adding chapters to the course content
- Adding badges to the chapters 
- Contents shall be addeble, editable and deletable.

Current version:
![image](https://user-images.githubusercontent.com/63921045/161760904-6d50e2ba-5fe5-4ae6-8892-052d6fabd186.png)

**Comment by Brunettow** [comment]
Requirements that are covered by the use case diagram:
* 2.1.2.2.2. System shall keep a predefined list of badges that can be earned by user.
* 2.1.2.2.3. Users will gain a badge when one the following occurs: learner completes a course, learner completes one section of the course, lecturer opens a new course, lecturer receives a review point that is greater than 4. (see 2.1.2.7.2.)
* 2.1.2.2.4. The system shall allow a lecturer to add more badges to the badge list of the course they created.
* 2.1.2.2.5. Achievement page shall be updated when a user gains a badge.

**Comment by Brunettow** [comment]
Diagram relations are reviewed and fixed:
![image](https://user-images.githubusercontent.com/63921045/162619424-582264e4-938d-4fec-8219-c599d6821e6b.png)
