### ISSUE TITLE
Class Diagram - EmailService

### ISSUE THREAD

**Issue by Brunettow** [bounswe/bounswe2022group3#77]
According to the [meeting notes](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%236-01.04.2022), Email Service in class diagram shall be prepared. This shall describe how the email service is connected to the other services.

Deadline: 03.04.2022 - 23.59
Reviewer: @hsuleerkul

**Comment by Brunettow** [comment]
Description of the class EmailService

Expected requirements from ... class --
1. It shall send a verification email to a user's email address.
2. It shall send an email to the user's email address that contains a link to change the password

## Fields
| Field| Type | Description|
| ---| ---| ---| 

## Methods
| Method| Args | Return |  Description|
| ---| ---| ---| ---|
|sendMail |user_id: int, mailType: String|null |This is the public method for sending emails. It calls sendConfirmationMail or sendChangePassMail according to mailType that is given as a variable. |
|sendConfirmationMail |user_id: int |null |This method prepares a message content that contains a link to verify the account. It calls send method and gives the message content to the method as a parameter. | 
|sendChangePassMail |user_id: int |null |This method prepares a message content that contains a link to change the account password. It calls send method and gives the message content to the method as a parameter. | 
|send|int user_id, string content|null|This method sends an email to the given user's email address with the provided message content. |

**Comment by Brunettow** [comment]
Finalized version:
![image](https://user-images.githubusercontent.com/63921045/161757293-1d6ba967-05b9-4fbf-bb7e-8b2d95bc5f1f.png)

**Comment by hsuleerkul** [comment]
Good job! This diagram matches what we talked about in [Meeting#7](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%237-04.04.2022), therefore I will close the issue.
