### ISSUE TITLE
Use Case Diagram - Create Profile

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#89]
As stated in [Meeting Notes #6 01.04.2022](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%236-01.04.2022), we should prepare a use case diagram to clearly understand and express users' actions in our platform. This issue focuses on creating profile pages.

What we need to cover:

- Setting up Bio information,
- Setting up Interest and Knowledge lists,
- Setting up profile privacy.

Deadline: 03.04.2022 - 23.59
Review Deadline: 05.04.2022 - 23.59

**Comment by ersoykadir** [comment]
<img src="https://user-images.githubusercontent.com/49765256/161445901-da73a5f0-86d0-4f85-85e4-d0cfccb220bb.png" width=80% height=80%>

First Draft is up. After the team review it will be modified and updated if necessary.

**Comment by mertcan-ozkan** [comment]
We may consider merging this use case with ["View Profile, Edit Profile"](https://github.com/bounswe/bounswe2022group3/issues/80) .Since view profile use cases seem to mostly cover create  profile use cases if we edit them slightly. We should consider this in the meeting in 04.04.2022.

**Comment by ersoykadir** [comment]
> We may consider merging this use case with ["View Profile, Edit Profile"](https://github.com/bounswe/bounswe2022group3/issues/80) .Since view profile use cases seem to mostly cover create profile use cases if we edit them slightly. We should consider this in the meeting in 04.04.2022.

## Team Review
After considering this comment. we connected the Create Profile use case to #80
![image](https://user-images.githubusercontent.com/49765256/161972321-19283222-9081-4067-bf45-6ab09ed63646.png)
