### ISSUE TITLE
Use Case Diagram - Login / Sign in

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#91]
### Task: 
As stated in [meeting notes 6](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%236-01.04.2022), we should prepare a use case diagram. This issue is about the login part of the whole diagram. 

The scope of this issue:
- Provide e-mail and password (See [Requirements 1.1.2.1](https://github.com/bounswe/bounswe2022group3/wiki/Requirements)).
- Login using Facebook, Twitter, Google (See [Requiremetns 1.1.2.2](https://github.com/bounswe/bounswe2022group3/wiki/Requirements)).
- Entering the wrong password 3 times. (See [Requirements 1.1.2.3](https://github.com/bounswe/bounswe2022group3/wiki/Requirements))

### Required Tools:
[Lucid.app](https://lucid.app/)

### Deadline:
4 April 2022, 23.59

**Comment by salimtirit** [comment]
![image](https://user-images.githubusercontent.com/64011660/161625251-c04ad21e-0d01-4766-8cd7-3d2b3e992dc0.png)
The first draft is up. After the team review, it will be modified and updated if necessary.

**Comment by hsuleerkul** [comment]
We decided that, forget password condition should be provoked after entering wrong password 3 times.

**Comment by salimtirit** [comment]
Reviewed with the group all look good.
