### ISSUE TITLE
Class Diagram - AuthorizationService

### ISSUE THREAD

**Issue by salimtirit** [bounswe/bounswe2022group3#94]
### Task: 
As stated in [meeting notes 6](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%236-01.04.2022), we should prepare class diagrams to understand how the implementation of the project will be.

AuthorizationService is a key service in our system. In any action that is taking place, AuthorizationService will be used to understand if the user is authorized to perform that action. 

The class diagram for AuthorizationService shall show the methods, fields, and variables it will have. It also needs to be connected to other classes. 

Expected requirements from AuthorizationService class:

1. It shall store information about which user is authorized to do what.
2. It shall have a function that grand access. 
3. It shall have functions that allow or prohibits users to do the wanted action.

### Required Tools:
[Lucid.app](https://lucid.app/)

### Deadline:
5 April 2022, 23.59

**Comment by yilmaz-burak** [comment]
In the customer meeting, according to the request, we have decided to remove this service from our diagram. Thanks for your effort Salim!
