### ISSUE TITLE
Class Diagram - Badge Class

### ISSUE THREAD

**Issue by hsuleerkul** [bounswe/bounswe2022group3#99]
According to the discussion between me and @muhammetssen (see issue #97), `Badge` class should be described by explaining the class structure and drawing its diagram.
 
This class is used to store user's achievements as badges. The badges will be displayed in a user's personal information page. There are two types of badges : 
1. Predefined badges : 
The badges in this category are created by the system and they will be same for each user. Some examples:
    - You have completed 5 courses.
    - You have created your first course.
    - You have created a discussion.
    - You got a rating above 4/5.
2. Custom badges : 
The badges in this category are created and customized by the course lecturer.
    - Course lecturer will be able to create new badges and assign them to chapters.
    - Users will gain these badges when they complete the chapters with a badge. 
    - These badges will be shown in the user's personal information. 
    
## Fields
| Field| Type | Description|
| ---| ---| ---| 
| badge_id | UID | ID of the badge |
| title | string | The title of a badge. It will be showed on the personal information page. | 
| description | string | A brief description about why this badge is given.  |
| creation_date | Date | The date this badge instance is created. |

## Methods

There are no methods of this class other than constructor.

**Deadline:** 05.04.2022 17.00

**Comment by hsuleerkul** [comment]
Badge class is created. It is ready for reviews!

![badgeclass](https://user-images.githubusercontent.com/56507424/161713887-f72ac2cf-ee80-407b-8280-dd15f7a436cb.PNG)

**Comment by bilalcim** [comment]
I understand that when a user gets a badge that is gained from _one_ course, for example, when a user gets a rating above 4/5 in some particular course, the course information will be saved in the description of the badge. Is this because some achievements may be gained from _one_ course, some from _more_, and some from _discussions_?

I guess the descriptions of badges will be generic (like gap-filling) and parseable so that when the users want to see their achievements in a specific course, we can easily show the relevant badges, right?

**Comment by ersoykadir** [comment]
What is the trigger for badges to be given to a user? To state more clearly,
- Predefined badges
  - How do we detect if a user completed 5 courses?
- Custom badges
  - Trigger for custom badges is more trivial, when a chapter is finished (I guess we need a chapterFinish function) we need to add the related badge_id of that chapter to the earned_badges of user

**Comment by hsuleerkul** [comment]
This issue has been reviewed by the team members in [meeting 8](), and it is finalized as shown below: 
![badgefinal](https://user-images.githubusercontent.com/56507424/161963308-c45ee789-57bf-4fa1-becd-a4d0265d7218.PNG)
